// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assetCollection.proto

package ca.wise.project.proto;

/**
 * Protobuf type {@code WISE.ProjectProto.AssetCollection}
 */
public final class AssetCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.ProjectProto.AssetCollection)
    AssetCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssetCollection.newBuilder() to construct.
  private AssetCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssetCollection() {
    assets_ = java.util.Collections.emptyList();
    valuesAtRisk_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AssetCollection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AssetCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              assets_ = new java.util.ArrayList<ca.wise.project.proto.ProjectAsset>();
              mutable_bitField0_ |= 0x00000001;
            }
            assets_.add(
                input.readMessage(ca.wise.project.proto.ProjectAsset.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              valuesAtRisk_ = new java.util.ArrayList<ca.wise.grid.proto.CwfgmAsset>();
              mutable_bitField0_ |= 0x00000002;
            }
            valuesAtRisk_.add(
                input.readMessage(ca.wise.grid.proto.CwfgmAsset.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        assets_ = java.util.Collections.unmodifiableList(assets_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        valuesAtRisk_ = java.util.Collections.unmodifiableList(valuesAtRisk_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_AssetCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_AssetCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.project.proto.AssetCollection.class, ca.wise.project.proto.AssetCollection.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int ASSETS_FIELD_NUMBER = 2;
  private java.util.List<ca.wise.project.proto.ProjectAsset> assets_;
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<ca.wise.project.proto.ProjectAsset> getAssetsList() {
    return assets_;
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<? extends ca.wise.project.proto.ProjectAssetOrBuilder> 
      getAssetsOrBuilderList() {
    return assets_;
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public int getAssetsCount() {
    return assets_.size();
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public ca.wise.project.proto.ProjectAsset getAssets(int index) {
    return assets_.get(index);
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public ca.wise.project.proto.ProjectAssetOrBuilder getAssetsOrBuilder(
      int index) {
    return assets_.get(index);
  }

  public static final int VALUESATRISK_FIELD_NUMBER = 3;
  private java.util.List<ca.wise.grid.proto.CwfgmAsset> valuesAtRisk_;
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  @java.lang.Override
  public java.util.List<ca.wise.grid.proto.CwfgmAsset> getValuesAtRiskList() {
    return valuesAtRisk_;
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ca.wise.grid.proto.CwfgmAssetOrBuilder> 
      getValuesAtRiskOrBuilderList() {
    return valuesAtRisk_;
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  @java.lang.Override
  public int getValuesAtRiskCount() {
    return valuesAtRisk_.size();
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmAsset getValuesAtRisk(int index) {
    return valuesAtRisk_.get(index);
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmAssetOrBuilder getValuesAtRiskOrBuilder(
      int index) {
    return valuesAtRisk_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    for (int i = 0; i < assets_.size(); i++) {
      output.writeMessage(2, assets_.get(i));
    }
    for (int i = 0; i < valuesAtRisk_.size(); i++) {
      output.writeMessage(3, valuesAtRisk_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    for (int i = 0; i < assets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, assets_.get(i));
    }
    for (int i = 0; i < valuesAtRisk_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, valuesAtRisk_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.project.proto.AssetCollection)) {
      return super.equals(obj);
    }
    ca.wise.project.proto.AssetCollection other = (ca.wise.project.proto.AssetCollection) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getAssetsList()
        .equals(other.getAssetsList())) return false;
    if (!getValuesAtRiskList()
        .equals(other.getValuesAtRiskList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (getAssetsCount() > 0) {
      hash = (37 * hash) + ASSETS_FIELD_NUMBER;
      hash = (53 * hash) + getAssetsList().hashCode();
    }
    if (getValuesAtRiskCount() > 0) {
      hash = (37 * hash) + VALUESATRISK_FIELD_NUMBER;
      hash = (53 * hash) + getValuesAtRiskList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.project.proto.AssetCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.AssetCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.AssetCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.AssetCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.project.proto.AssetCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.AssetCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.AssetCollection)
      ca.wise.project.proto.AssetCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_AssetCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_AssetCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.AssetCollection.class, ca.wise.project.proto.AssetCollection.Builder.class);
    }

    // Construct using ca.wise.project.proto.AssetCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAssetsFieldBuilder();
        getValuesAtRiskFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (assetsBuilder_ == null) {
        assets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        assetsBuilder_.clear();
      }
      if (valuesAtRiskBuilder_ == null) {
        valuesAtRisk_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        valuesAtRiskBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_AssetCollection_descriptor;
    }

    @java.lang.Override
    public ca.wise.project.proto.AssetCollection getDefaultInstanceForType() {
      return ca.wise.project.proto.AssetCollection.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.project.proto.AssetCollection build() {
      ca.wise.project.proto.AssetCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.project.proto.AssetCollection buildPartial() {
      ca.wise.project.proto.AssetCollection result = new ca.wise.project.proto.AssetCollection(this);
      int from_bitField0_ = bitField0_;
      result.version_ = version_;
      if (assetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          assets_ = java.util.Collections.unmodifiableList(assets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.assets_ = assets_;
      } else {
        result.assets_ = assetsBuilder_.build();
      }
      if (valuesAtRiskBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          valuesAtRisk_ = java.util.Collections.unmodifiableList(valuesAtRisk_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.valuesAtRisk_ = valuesAtRisk_;
      } else {
        result.valuesAtRisk_ = valuesAtRiskBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.project.proto.AssetCollection) {
        return mergeFrom((ca.wise.project.proto.AssetCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.project.proto.AssetCollection other) {
      if (other == ca.wise.project.proto.AssetCollection.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (assetsBuilder_ == null) {
        if (!other.assets_.isEmpty()) {
          if (assets_.isEmpty()) {
            assets_ = other.assets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAssetsIsMutable();
            assets_.addAll(other.assets_);
          }
          onChanged();
        }
      } else {
        if (!other.assets_.isEmpty()) {
          if (assetsBuilder_.isEmpty()) {
            assetsBuilder_.dispose();
            assetsBuilder_ = null;
            assets_ = other.assets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            assetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAssetsFieldBuilder() : null;
          } else {
            assetsBuilder_.addAllMessages(other.assets_);
          }
        }
      }
      if (valuesAtRiskBuilder_ == null) {
        if (!other.valuesAtRisk_.isEmpty()) {
          if (valuesAtRisk_.isEmpty()) {
            valuesAtRisk_ = other.valuesAtRisk_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesAtRiskIsMutable();
            valuesAtRisk_.addAll(other.valuesAtRisk_);
          }
          onChanged();
        }
      } else {
        if (!other.valuesAtRisk_.isEmpty()) {
          if (valuesAtRiskBuilder_.isEmpty()) {
            valuesAtRiskBuilder_.dispose();
            valuesAtRiskBuilder_ = null;
            valuesAtRisk_ = other.valuesAtRisk_;
            bitField0_ = (bitField0_ & ~0x00000002);
            valuesAtRiskBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValuesAtRiskFieldBuilder() : null;
          } else {
            valuesAtRiskBuilder_.addAllMessages(other.valuesAtRisk_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.project.proto.AssetCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.project.proto.AssetCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<ca.wise.project.proto.ProjectAsset> assets_ =
      java.util.Collections.emptyList();
    private void ensureAssetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        assets_ = new java.util.ArrayList<ca.wise.project.proto.ProjectAsset>(assets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.project.proto.ProjectAsset, ca.wise.project.proto.ProjectAsset.Builder, ca.wise.project.proto.ProjectAssetOrBuilder> assetsBuilder_;

    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<ca.wise.project.proto.ProjectAsset> getAssetsList() {
      if (assetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(assets_);
      } else {
        return assetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public int getAssetsCount() {
      if (assetsBuilder_ == null) {
        return assets_.size();
      } else {
        return assetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.ProjectAsset getAssets(int index) {
      if (assetsBuilder_ == null) {
        return assets_.get(index);
      } else {
        return assetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setAssets(
        int index, ca.wise.project.proto.ProjectAsset value) {
      if (assetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetsIsMutable();
        assets_.set(index, value);
        onChanged();
      } else {
        assetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setAssets(
        int index, ca.wise.project.proto.ProjectAsset.Builder builderForValue) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.set(index, builderForValue.build());
        onChanged();
      } else {
        assetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAssets(ca.wise.project.proto.ProjectAsset value) {
      if (assetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetsIsMutable();
        assets_.add(value);
        onChanged();
      } else {
        assetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAssets(
        int index, ca.wise.project.proto.ProjectAsset value) {
      if (assetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssetsIsMutable();
        assets_.add(index, value);
        onChanged();
      } else {
        assetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAssets(
        ca.wise.project.proto.ProjectAsset.Builder builderForValue) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.add(builderForValue.build());
        onChanged();
      } else {
        assetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAssets(
        int index, ca.wise.project.proto.ProjectAsset.Builder builderForValue) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.add(index, builderForValue.build());
        onChanged();
      } else {
        assetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAllAssets(
        java.lang.Iterable<? extends ca.wise.project.proto.ProjectAsset> values) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, assets_);
        onChanged();
      } else {
        assetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearAssets() {
      if (assetsBuilder_ == null) {
        assets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        assetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder removeAssets(int index) {
      if (assetsBuilder_ == null) {
        ensureAssetsIsMutable();
        assets_.remove(index);
        onChanged();
      } else {
        assetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.ProjectAsset.Builder getAssetsBuilder(
        int index) {
      return getAssetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.ProjectAssetOrBuilder getAssetsOrBuilder(
        int index) {
      if (assetsBuilder_ == null) {
        return assets_.get(index);  } else {
        return assetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<? extends ca.wise.project.proto.ProjectAssetOrBuilder> 
         getAssetsOrBuilderList() {
      if (assetsBuilder_ != null) {
        return assetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(assets_);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.ProjectAsset.Builder addAssetsBuilder() {
      return getAssetsFieldBuilder().addBuilder(
          ca.wise.project.proto.ProjectAsset.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.ProjectAsset.Builder addAssetsBuilder(
        int index) {
      return getAssetsFieldBuilder().addBuilder(
          index, ca.wise.project.proto.ProjectAsset.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<ca.wise.project.proto.ProjectAsset.Builder> 
         getAssetsBuilderList() {
      return getAssetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.project.proto.ProjectAsset, ca.wise.project.proto.ProjectAsset.Builder, ca.wise.project.proto.ProjectAssetOrBuilder> 
        getAssetsFieldBuilder() {
      if (assetsBuilder_ == null) {
        assetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.project.proto.ProjectAsset, ca.wise.project.proto.ProjectAsset.Builder, ca.wise.project.proto.ProjectAssetOrBuilder>(
                assets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        assets_ = null;
      }
      return assetsBuilder_;
    }

    private java.util.List<ca.wise.grid.proto.CwfgmAsset> valuesAtRisk_ =
      java.util.Collections.emptyList();
    private void ensureValuesAtRiskIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        valuesAtRisk_ = new java.util.ArrayList<ca.wise.grid.proto.CwfgmAsset>(valuesAtRisk_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.grid.proto.CwfgmAsset, ca.wise.grid.proto.CwfgmAsset.Builder, ca.wise.grid.proto.CwfgmAssetOrBuilder> valuesAtRiskBuilder_;

    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public java.util.List<ca.wise.grid.proto.CwfgmAsset> getValuesAtRiskList() {
      if (valuesAtRiskBuilder_ == null) {
        return java.util.Collections.unmodifiableList(valuesAtRisk_);
      } else {
        return valuesAtRiskBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public int getValuesAtRiskCount() {
      if (valuesAtRiskBuilder_ == null) {
        return valuesAtRisk_.size();
      } else {
        return valuesAtRiskBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmAsset getValuesAtRisk(int index) {
      if (valuesAtRiskBuilder_ == null) {
        return valuesAtRisk_.get(index);
      } else {
        return valuesAtRiskBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder setValuesAtRisk(
        int index, ca.wise.grid.proto.CwfgmAsset value) {
      if (valuesAtRiskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.set(index, value);
        onChanged();
      } else {
        valuesAtRiskBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder setValuesAtRisk(
        int index, ca.wise.grid.proto.CwfgmAsset.Builder builderForValue) {
      if (valuesAtRiskBuilder_ == null) {
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.set(index, builderForValue.build());
        onChanged();
      } else {
        valuesAtRiskBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder addValuesAtRisk(ca.wise.grid.proto.CwfgmAsset value) {
      if (valuesAtRiskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.add(value);
        onChanged();
      } else {
        valuesAtRiskBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder addValuesAtRisk(
        int index, ca.wise.grid.proto.CwfgmAsset value) {
      if (valuesAtRiskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.add(index, value);
        onChanged();
      } else {
        valuesAtRiskBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder addValuesAtRisk(
        ca.wise.grid.proto.CwfgmAsset.Builder builderForValue) {
      if (valuesAtRiskBuilder_ == null) {
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.add(builderForValue.build());
        onChanged();
      } else {
        valuesAtRiskBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder addValuesAtRisk(
        int index, ca.wise.grid.proto.CwfgmAsset.Builder builderForValue) {
      if (valuesAtRiskBuilder_ == null) {
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.add(index, builderForValue.build());
        onChanged();
      } else {
        valuesAtRiskBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder addAllValuesAtRisk(
        java.lang.Iterable<? extends ca.wise.grid.proto.CwfgmAsset> values) {
      if (valuesAtRiskBuilder_ == null) {
        ensureValuesAtRiskIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, valuesAtRisk_);
        onChanged();
      } else {
        valuesAtRiskBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder clearValuesAtRisk() {
      if (valuesAtRiskBuilder_ == null) {
        valuesAtRisk_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        valuesAtRiskBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public Builder removeValuesAtRisk(int index) {
      if (valuesAtRiskBuilder_ == null) {
        ensureValuesAtRiskIsMutable();
        valuesAtRisk_.remove(index);
        onChanged();
      } else {
        valuesAtRiskBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmAsset.Builder getValuesAtRiskBuilder(
        int index) {
      return getValuesAtRiskFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmAssetOrBuilder getValuesAtRiskOrBuilder(
        int index) {
      if (valuesAtRiskBuilder_ == null) {
        return valuesAtRisk_.get(index);  } else {
        return valuesAtRiskBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public java.util.List<? extends ca.wise.grid.proto.CwfgmAssetOrBuilder> 
         getValuesAtRiskOrBuilderList() {
      if (valuesAtRiskBuilder_ != null) {
        return valuesAtRiskBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(valuesAtRisk_);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmAsset.Builder addValuesAtRiskBuilder() {
      return getValuesAtRiskFieldBuilder().addBuilder(
          ca.wise.grid.proto.CwfgmAsset.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmAsset.Builder addValuesAtRiskBuilder(
        int index) {
      return getValuesAtRiskFieldBuilder().addBuilder(
          index, ca.wise.grid.proto.CwfgmAsset.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
     */
    public java.util.List<ca.wise.grid.proto.CwfgmAsset.Builder> 
         getValuesAtRiskBuilderList() {
      return getValuesAtRiskFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.grid.proto.CwfgmAsset, ca.wise.grid.proto.CwfgmAsset.Builder, ca.wise.grid.proto.CwfgmAssetOrBuilder> 
        getValuesAtRiskFieldBuilder() {
      if (valuesAtRiskBuilder_ == null) {
        valuesAtRiskBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.grid.proto.CwfgmAsset, ca.wise.grid.proto.CwfgmAsset.Builder, ca.wise.grid.proto.CwfgmAssetOrBuilder>(
                valuesAtRisk_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        valuesAtRisk_ = null;
      }
      return valuesAtRiskBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.AssetCollection)
  }

  // @@protoc_insertion_point(class_scope:WISE.ProjectProto.AssetCollection)
  private static final ca.wise.project.proto.AssetCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.project.proto.AssetCollection();
  }

  public static ca.wise.project.proto.AssetCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetCollection>
      PARSER = new com.google.protobuf.AbstractParser<AssetCollection>() {
    @java.lang.Override
    public AssetCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AssetCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AssetCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.project.proto.AssetCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

