// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assetCollection.proto

package ca.wise.project.proto;

public interface AssetCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.AssetCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<ca.wise.project.proto.ProjectAsset> 
      getAssetsList();
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated ca.wise.project.proto.ProjectAsset getAssets(int index);
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated int getAssetsCount();
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.util.List<? extends ca.wise.project.proto.ProjectAssetOrBuilder> 
      getAssetsOrBuilderList();
  /**
   * <code>repeated .WISE.ProjectProto.ProjectAsset assets = 2 [deprecated = true];</code>
   */
  @java.lang.Deprecated ca.wise.project.proto.ProjectAssetOrBuilder getAssetsOrBuilder(
      int index);

  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  java.util.List<ca.wise.grid.proto.CwfgmAsset> 
      getValuesAtRiskList();
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  ca.wise.grid.proto.CwfgmAsset getValuesAtRisk(int index);
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  int getValuesAtRiskCount();
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  java.util.List<? extends ca.wise.grid.proto.CwfgmAssetOrBuilder> 
      getValuesAtRiskOrBuilderList();
  /**
   * <code>repeated .WISE.GridProto.CwfgmAsset valuesAtRisk = 3;</code>
   */
  ca.wise.grid.proto.CwfgmAssetOrBuilder getValuesAtRiskOrBuilder(
      int index);
}
