// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fuelCollection.proto

package ca.wise.project.proto;

/**
 * Protobuf type {@code WISE.ProjectProto.FuelCollection}
 */
@java.lang.Deprecated public final class FuelCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.ProjectProto.FuelCollection)
    FuelCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FuelCollection.newBuilder() to construct.
  private FuelCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FuelCollection() {
    fuels_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FuelCollection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FuelCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (importedLut_ != null) {
              subBuilder = importedLut_.toBuilder();
            }
            importedLut_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(importedLut_);
              importedLut_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (showUnused_ != null) {
              subBuilder = showUnused_.toBuilder();
            }
            showUnused_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(showUnused_);
              showUnused_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (lutFilename_ != null) {
              subBuilder = lutFilename_.toBuilder();
            }
            lutFilename_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lutFilename_);
              lutFilename_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fuels_ = new java.util.ArrayList<ca.wise.project.proto.ProjectFuel>();
              mutable_bitField0_ |= 0x00000001;
            }
            fuels_.add(
                input.readMessage(ca.wise.project.proto.ProjectFuel.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fuels_ = java.util.Collections.unmodifiableList(fuels_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.project.proto.FuelCollectionOuterClass.internal_static_WISE_ProjectProto_FuelCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.project.proto.FuelCollectionOuterClass.internal_static_WISE_ProjectProto_FuelCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.project.proto.FuelCollection.class, ca.wise.project.proto.FuelCollection.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int IMPORTEDLUT_FIELD_NUMBER = 2;
  private com.google.protobuf.BoolValue importedLut_;
  /**
   * <code>.google.protobuf.BoolValue importedLut = 2;</code>
   * @return Whether the importedLut field is set.
   */
  @java.lang.Override
  public boolean hasImportedLut() {
    return importedLut_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue importedLut = 2;</code>
   * @return The importedLut.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getImportedLut() {
    return importedLut_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : importedLut_;
  }
  /**
   * <code>.google.protobuf.BoolValue importedLut = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getImportedLutOrBuilder() {
    return getImportedLut();
  }

  public static final int SHOWUNUSED_FIELD_NUMBER = 3;
  private com.google.protobuf.BoolValue showUnused_;
  /**
   * <code>.google.protobuf.BoolValue showUnused = 3;</code>
   * @return Whether the showUnused field is set.
   */
  @java.lang.Override
  public boolean hasShowUnused() {
    return showUnused_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue showUnused = 3;</code>
   * @return The showUnused.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getShowUnused() {
    return showUnused_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : showUnused_;
  }
  /**
   * <code>.google.protobuf.BoolValue showUnused = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getShowUnusedOrBuilder() {
    return getShowUnused();
  }

  public static final int LUTFILENAME_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue lutFilename_;
  /**
   * <code>.google.protobuf.StringValue lutFilename = 4;</code>
   * @return Whether the lutFilename field is set.
   */
  @java.lang.Override
  public boolean hasLutFilename() {
    return lutFilename_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue lutFilename = 4;</code>
   * @return The lutFilename.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getLutFilename() {
    return lutFilename_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : lutFilename_;
  }
  /**
   * <code>.google.protobuf.StringValue lutFilename = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getLutFilenameOrBuilder() {
    return getLutFilename();
  }

  public static final int FUELS_FIELD_NUMBER = 5;
  private java.util.List<ca.wise.project.proto.ProjectFuel> fuels_;
  /**
   * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
   */
  @java.lang.Override
  public java.util.List<ca.wise.project.proto.ProjectFuel> getFuelsList() {
    return fuels_;
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ca.wise.project.proto.ProjectFuelOrBuilder> 
      getFuelsOrBuilderList() {
    return fuels_;
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
   */
  @java.lang.Override
  public int getFuelsCount() {
    return fuels_.size();
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
   */
  @java.lang.Override
  public ca.wise.project.proto.ProjectFuel getFuels(int index) {
    return fuels_.get(index);
  }
  /**
   * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
   */
  @java.lang.Override
  public ca.wise.project.proto.ProjectFuelOrBuilder getFuelsOrBuilder(
      int index) {
    return fuels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (importedLut_ != null) {
      output.writeMessage(2, getImportedLut());
    }
    if (showUnused_ != null) {
      output.writeMessage(3, getShowUnused());
    }
    if (lutFilename_ != null) {
      output.writeMessage(4, getLutFilename());
    }
    for (int i = 0; i < fuels_.size(); i++) {
      output.writeMessage(5, fuels_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (importedLut_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getImportedLut());
    }
    if (showUnused_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getShowUnused());
    }
    if (lutFilename_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLutFilename());
    }
    for (int i = 0; i < fuels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, fuels_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.project.proto.FuelCollection)) {
      return super.equals(obj);
    }
    ca.wise.project.proto.FuelCollection other = (ca.wise.project.proto.FuelCollection) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasImportedLut() != other.hasImportedLut()) return false;
    if (hasImportedLut()) {
      if (!getImportedLut()
          .equals(other.getImportedLut())) return false;
    }
    if (hasShowUnused() != other.hasShowUnused()) return false;
    if (hasShowUnused()) {
      if (!getShowUnused()
          .equals(other.getShowUnused())) return false;
    }
    if (hasLutFilename() != other.hasLutFilename()) return false;
    if (hasLutFilename()) {
      if (!getLutFilename()
          .equals(other.getLutFilename())) return false;
    }
    if (!getFuelsList()
        .equals(other.getFuelsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (hasImportedLut()) {
      hash = (37 * hash) + IMPORTEDLUT_FIELD_NUMBER;
      hash = (53 * hash) + getImportedLut().hashCode();
    }
    if (hasShowUnused()) {
      hash = (37 * hash) + SHOWUNUSED_FIELD_NUMBER;
      hash = (53 * hash) + getShowUnused().hashCode();
    }
    if (hasLutFilename()) {
      hash = (37 * hash) + LUTFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getLutFilename().hashCode();
    }
    if (getFuelsCount() > 0) {
      hash = (37 * hash) + FUELS_FIELD_NUMBER;
      hash = (53 * hash) + getFuelsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.project.proto.FuelCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.FuelCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.FuelCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.FuelCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.project.proto.FuelCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.FuelCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.FuelCollection)
      ca.wise.project.proto.FuelCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.FuelCollectionOuterClass.internal_static_WISE_ProjectProto_FuelCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.FuelCollectionOuterClass.internal_static_WISE_ProjectProto_FuelCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.FuelCollection.class, ca.wise.project.proto.FuelCollection.Builder.class);
    }

    // Construct using ca.wise.project.proto.FuelCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFuelsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (importedLutBuilder_ == null) {
        importedLut_ = null;
      } else {
        importedLut_ = null;
        importedLutBuilder_ = null;
      }
      if (showUnusedBuilder_ == null) {
        showUnused_ = null;
      } else {
        showUnused_ = null;
        showUnusedBuilder_ = null;
      }
      if (lutFilenameBuilder_ == null) {
        lutFilename_ = null;
      } else {
        lutFilename_ = null;
        lutFilenameBuilder_ = null;
      }
      if (fuelsBuilder_ == null) {
        fuels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fuelsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.project.proto.FuelCollectionOuterClass.internal_static_WISE_ProjectProto_FuelCollection_descriptor;
    }

    @java.lang.Override
    public ca.wise.project.proto.FuelCollection getDefaultInstanceForType() {
      return ca.wise.project.proto.FuelCollection.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.project.proto.FuelCollection build() {
      ca.wise.project.proto.FuelCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.project.proto.FuelCollection buildPartial() {
      ca.wise.project.proto.FuelCollection result = new ca.wise.project.proto.FuelCollection(this);
      int from_bitField0_ = bitField0_;
      result.version_ = version_;
      if (importedLutBuilder_ == null) {
        result.importedLut_ = importedLut_;
      } else {
        result.importedLut_ = importedLutBuilder_.build();
      }
      if (showUnusedBuilder_ == null) {
        result.showUnused_ = showUnused_;
      } else {
        result.showUnused_ = showUnusedBuilder_.build();
      }
      if (lutFilenameBuilder_ == null) {
        result.lutFilename_ = lutFilename_;
      } else {
        result.lutFilename_ = lutFilenameBuilder_.build();
      }
      if (fuelsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fuels_ = java.util.Collections.unmodifiableList(fuels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fuels_ = fuels_;
      } else {
        result.fuels_ = fuelsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.project.proto.FuelCollection) {
        return mergeFrom((ca.wise.project.proto.FuelCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.project.proto.FuelCollection other) {
      if (other == ca.wise.project.proto.FuelCollection.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.hasImportedLut()) {
        mergeImportedLut(other.getImportedLut());
      }
      if (other.hasShowUnused()) {
        mergeShowUnused(other.getShowUnused());
      }
      if (other.hasLutFilename()) {
        mergeLutFilename(other.getLutFilename());
      }
      if (fuelsBuilder_ == null) {
        if (!other.fuels_.isEmpty()) {
          if (fuels_.isEmpty()) {
            fuels_ = other.fuels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFuelsIsMutable();
            fuels_.addAll(other.fuels_);
          }
          onChanged();
        }
      } else {
        if (!other.fuels_.isEmpty()) {
          if (fuelsBuilder_.isEmpty()) {
            fuelsBuilder_.dispose();
            fuelsBuilder_ = null;
            fuels_ = other.fuels_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fuelsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFuelsFieldBuilder() : null;
          } else {
            fuelsBuilder_.addAllMessages(other.fuels_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.project.proto.FuelCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.project.proto.FuelCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.BoolValue importedLut_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> importedLutBuilder_;
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     * @return Whether the importedLut field is set.
     */
    public boolean hasImportedLut() {
      return importedLutBuilder_ != null || importedLut_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     * @return The importedLut.
     */
    public com.google.protobuf.BoolValue getImportedLut() {
      if (importedLutBuilder_ == null) {
        return importedLut_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : importedLut_;
      } else {
        return importedLutBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    public Builder setImportedLut(com.google.protobuf.BoolValue value) {
      if (importedLutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        importedLut_ = value;
        onChanged();
      } else {
        importedLutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    public Builder setImportedLut(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (importedLutBuilder_ == null) {
        importedLut_ = builderForValue.build();
        onChanged();
      } else {
        importedLutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    public Builder mergeImportedLut(com.google.protobuf.BoolValue value) {
      if (importedLutBuilder_ == null) {
        if (importedLut_ != null) {
          importedLut_ =
            com.google.protobuf.BoolValue.newBuilder(importedLut_).mergeFrom(value).buildPartial();
        } else {
          importedLut_ = value;
        }
        onChanged();
      } else {
        importedLutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    public Builder clearImportedLut() {
      if (importedLutBuilder_ == null) {
        importedLut_ = null;
        onChanged();
      } else {
        importedLut_ = null;
        importedLutBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    public com.google.protobuf.BoolValue.Builder getImportedLutBuilder() {
      
      onChanged();
      return getImportedLutFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getImportedLutOrBuilder() {
      if (importedLutBuilder_ != null) {
        return importedLutBuilder_.getMessageOrBuilder();
      } else {
        return importedLut_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : importedLut_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue importedLut = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getImportedLutFieldBuilder() {
      if (importedLutBuilder_ == null) {
        importedLutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getImportedLut(),
                getParentForChildren(),
                isClean());
        importedLut_ = null;
      }
      return importedLutBuilder_;
    }

    private com.google.protobuf.BoolValue showUnused_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> showUnusedBuilder_;
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     * @return Whether the showUnused field is set.
     */
    public boolean hasShowUnused() {
      return showUnusedBuilder_ != null || showUnused_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     * @return The showUnused.
     */
    public com.google.protobuf.BoolValue getShowUnused() {
      if (showUnusedBuilder_ == null) {
        return showUnused_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : showUnused_;
      } else {
        return showUnusedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    public Builder setShowUnused(com.google.protobuf.BoolValue value) {
      if (showUnusedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        showUnused_ = value;
        onChanged();
      } else {
        showUnusedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    public Builder setShowUnused(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (showUnusedBuilder_ == null) {
        showUnused_ = builderForValue.build();
        onChanged();
      } else {
        showUnusedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    public Builder mergeShowUnused(com.google.protobuf.BoolValue value) {
      if (showUnusedBuilder_ == null) {
        if (showUnused_ != null) {
          showUnused_ =
            com.google.protobuf.BoolValue.newBuilder(showUnused_).mergeFrom(value).buildPartial();
        } else {
          showUnused_ = value;
        }
        onChanged();
      } else {
        showUnusedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    public Builder clearShowUnused() {
      if (showUnusedBuilder_ == null) {
        showUnused_ = null;
        onChanged();
      } else {
        showUnused_ = null;
        showUnusedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    public com.google.protobuf.BoolValue.Builder getShowUnusedBuilder() {
      
      onChanged();
      return getShowUnusedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getShowUnusedOrBuilder() {
      if (showUnusedBuilder_ != null) {
        return showUnusedBuilder_.getMessageOrBuilder();
      } else {
        return showUnused_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : showUnused_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue showUnused = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getShowUnusedFieldBuilder() {
      if (showUnusedBuilder_ == null) {
        showUnusedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getShowUnused(),
                getParentForChildren(),
                isClean());
        showUnused_ = null;
      }
      return showUnusedBuilder_;
    }

    private com.google.protobuf.StringValue lutFilename_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> lutFilenameBuilder_;
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     * @return Whether the lutFilename field is set.
     */
    public boolean hasLutFilename() {
      return lutFilenameBuilder_ != null || lutFilename_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     * @return The lutFilename.
     */
    public com.google.protobuf.StringValue getLutFilename() {
      if (lutFilenameBuilder_ == null) {
        return lutFilename_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : lutFilename_;
      } else {
        return lutFilenameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    public Builder setLutFilename(com.google.protobuf.StringValue value) {
      if (lutFilenameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lutFilename_ = value;
        onChanged();
      } else {
        lutFilenameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    public Builder setLutFilename(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (lutFilenameBuilder_ == null) {
        lutFilename_ = builderForValue.build();
        onChanged();
      } else {
        lutFilenameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    public Builder mergeLutFilename(com.google.protobuf.StringValue value) {
      if (lutFilenameBuilder_ == null) {
        if (lutFilename_ != null) {
          lutFilename_ =
            com.google.protobuf.StringValue.newBuilder(lutFilename_).mergeFrom(value).buildPartial();
        } else {
          lutFilename_ = value;
        }
        onChanged();
      } else {
        lutFilenameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    public Builder clearLutFilename() {
      if (lutFilenameBuilder_ == null) {
        lutFilename_ = null;
        onChanged();
      } else {
        lutFilename_ = null;
        lutFilenameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getLutFilenameBuilder() {
      
      onChanged();
      return getLutFilenameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getLutFilenameOrBuilder() {
      if (lutFilenameBuilder_ != null) {
        return lutFilenameBuilder_.getMessageOrBuilder();
      } else {
        return lutFilename_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : lutFilename_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue lutFilename = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getLutFilenameFieldBuilder() {
      if (lutFilenameBuilder_ == null) {
        lutFilenameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getLutFilename(),
                getParentForChildren(),
                isClean());
        lutFilename_ = null;
      }
      return lutFilenameBuilder_;
    }

    private java.util.List<ca.wise.project.proto.ProjectFuel> fuels_ =
      java.util.Collections.emptyList();
    private void ensureFuelsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fuels_ = new java.util.ArrayList<ca.wise.project.proto.ProjectFuel>(fuels_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.project.proto.ProjectFuel, ca.wise.project.proto.ProjectFuel.Builder, ca.wise.project.proto.ProjectFuelOrBuilder> fuelsBuilder_;

    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public java.util.List<ca.wise.project.proto.ProjectFuel> getFuelsList() {
      if (fuelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fuels_);
      } else {
        return fuelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public int getFuelsCount() {
      if (fuelsBuilder_ == null) {
        return fuels_.size();
      } else {
        return fuelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public ca.wise.project.proto.ProjectFuel getFuels(int index) {
      if (fuelsBuilder_ == null) {
        return fuels_.get(index);
      } else {
        return fuelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder setFuels(
        int index, ca.wise.project.proto.ProjectFuel value) {
      if (fuelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFuelsIsMutable();
        fuels_.set(index, value);
        onChanged();
      } else {
        fuelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder setFuels(
        int index, ca.wise.project.proto.ProjectFuel.Builder builderForValue) {
      if (fuelsBuilder_ == null) {
        ensureFuelsIsMutable();
        fuels_.set(index, builderForValue.build());
        onChanged();
      } else {
        fuelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder addFuels(ca.wise.project.proto.ProjectFuel value) {
      if (fuelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFuelsIsMutable();
        fuels_.add(value);
        onChanged();
      } else {
        fuelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder addFuels(
        int index, ca.wise.project.proto.ProjectFuel value) {
      if (fuelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFuelsIsMutable();
        fuels_.add(index, value);
        onChanged();
      } else {
        fuelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder addFuels(
        ca.wise.project.proto.ProjectFuel.Builder builderForValue) {
      if (fuelsBuilder_ == null) {
        ensureFuelsIsMutable();
        fuels_.add(builderForValue.build());
        onChanged();
      } else {
        fuelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder addFuels(
        int index, ca.wise.project.proto.ProjectFuel.Builder builderForValue) {
      if (fuelsBuilder_ == null) {
        ensureFuelsIsMutable();
        fuels_.add(index, builderForValue.build());
        onChanged();
      } else {
        fuelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder addAllFuels(
        java.lang.Iterable<? extends ca.wise.project.proto.ProjectFuel> values) {
      if (fuelsBuilder_ == null) {
        ensureFuelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fuels_);
        onChanged();
      } else {
        fuelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder clearFuels() {
      if (fuelsBuilder_ == null) {
        fuels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fuelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public Builder removeFuels(int index) {
      if (fuelsBuilder_ == null) {
        ensureFuelsIsMutable();
        fuels_.remove(index);
        onChanged();
      } else {
        fuelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public ca.wise.project.proto.ProjectFuel.Builder getFuelsBuilder(
        int index) {
      return getFuelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public ca.wise.project.proto.ProjectFuelOrBuilder getFuelsOrBuilder(
        int index) {
      if (fuelsBuilder_ == null) {
        return fuels_.get(index);  } else {
        return fuelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public java.util.List<? extends ca.wise.project.proto.ProjectFuelOrBuilder> 
         getFuelsOrBuilderList() {
      if (fuelsBuilder_ != null) {
        return fuelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fuels_);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public ca.wise.project.proto.ProjectFuel.Builder addFuelsBuilder() {
      return getFuelsFieldBuilder().addBuilder(
          ca.wise.project.proto.ProjectFuel.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public ca.wise.project.proto.ProjectFuel.Builder addFuelsBuilder(
        int index) {
      return getFuelsFieldBuilder().addBuilder(
          index, ca.wise.project.proto.ProjectFuel.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.ProjectProto.ProjectFuel fuels = 5;</code>
     */
    public java.util.List<ca.wise.project.proto.ProjectFuel.Builder> 
         getFuelsBuilderList() {
      return getFuelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.project.proto.ProjectFuel, ca.wise.project.proto.ProjectFuel.Builder, ca.wise.project.proto.ProjectFuelOrBuilder> 
        getFuelsFieldBuilder() {
      if (fuelsBuilder_ == null) {
        fuelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.project.proto.ProjectFuel, ca.wise.project.proto.ProjectFuel.Builder, ca.wise.project.proto.ProjectFuelOrBuilder>(
                fuels_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fuels_ = null;
      }
      return fuelsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.FuelCollection)
  }

  // @@protoc_insertion_point(class_scope:WISE.ProjectProto.FuelCollection)
  private static final ca.wise.project.proto.FuelCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.project.proto.FuelCollection();
  }

  public static ca.wise.project.proto.FuelCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FuelCollection>
      PARSER = new com.google.protobuf.AbstractParser<FuelCollection>() {
    @java.lang.Override
    public FuelCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FuelCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FuelCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FuelCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.project.proto.FuelCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

