// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectGridFilter.proto

package ca.wise.project.proto;

/**
 * Protobuf type {@code WISE.ProjectProto.ProjectPolyWeatherGridFilter}
 */
@java.lang.Deprecated public final class ProjectPolyWeatherGridFilter extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.ProjectProto.ProjectPolyWeatherGridFilter)
    ProjectPolyWeatherGridFilterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProjectPolyWeatherGridFilter.newBuilder() to construct.
  private ProjectPolyWeatherGridFilter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProjectPolyWeatherGridFilter() {
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProjectPolyWeatherGridFilter();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProjectPolyWeatherGridFilter(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            comments_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.UInt32Value.Builder subBuilder = null;
            if (color_ != null) {
              subBuilder = color_.toBuilder();
            }
            color_ = input.readMessage(com.google.protobuf.UInt32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(color_);
              color_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.UInt64Value.Builder subBuilder = null;
            if (size_ != null) {
              subBuilder = size_.toBuilder();
            }
            size_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(size_);
              size_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            landscape_ = input.readBool();
            break;
          }
          case 58: {
            ca.wise.weather.proto.WeatherGridFilter.Builder subBuilder = null;
            if (filter_ != null) {
              subBuilder = filter_.toBuilder();
            }
            filter_ = input.readMessage(ca.wise.weather.proto.WeatherGridFilter.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filter_);
              filter_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.project.proto.ProjectGridFilter.internal_static_WISE_ProjectProto_ProjectPolyWeatherGridFilter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.project.proto.ProjectGridFilter.internal_static_WISE_ProjectProto_ProjectPolyWeatherGridFilter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.project.proto.ProjectPolyWeatherGridFilter.class, ca.wise.project.proto.ProjectPolyWeatherGridFilter.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 3;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 3;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 3;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private com.google.protobuf.UInt32Value color_;
  /**
   * <code>.google.protobuf.UInt32Value color = 4;</code>
   * @return Whether the color field is set.
   */
  @java.lang.Override
  public boolean hasColor() {
    return color_ != null;
  }
  /**
   * <code>.google.protobuf.UInt32Value color = 4;</code>
   * @return The color.
   */
  @java.lang.Override
  public com.google.protobuf.UInt32Value getColor() {
    return color_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : color_;
  }
  /**
   * <code>.google.protobuf.UInt32Value color = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.UInt32ValueOrBuilder getColorOrBuilder() {
    return getColor();
  }

  public static final int SIZE_FIELD_NUMBER = 5;
  private com.google.protobuf.UInt64Value size_;
  /**
   * <code>.google.protobuf.UInt64Value size = 5;</code>
   * @return Whether the size field is set.
   */
  @java.lang.Override
  public boolean hasSize() {
    return size_ != null;
  }
  /**
   * <code>.google.protobuf.UInt64Value size = 5;</code>
   * @return The size.
   */
  @java.lang.Override
  public com.google.protobuf.UInt64Value getSize() {
    return size_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : size_;
  }
  /**
   * <code>.google.protobuf.UInt64Value size = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.UInt64ValueOrBuilder getSizeOrBuilder() {
    return getSize();
  }

  public static final int LANDSCAPE_FIELD_NUMBER = 6;
  private boolean landscape_;
  /**
   * <code>bool landscape = 6;</code>
   * @return The landscape.
   */
  @java.lang.Override
  public boolean getLandscape() {
    return landscape_;
  }

  public static final int FILTER_FIELD_NUMBER = 7;
  private ca.wise.weather.proto.WeatherGridFilter filter_;
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return filter_ != null;
  }
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
   * @return The filter.
   */
  @java.lang.Override
  public ca.wise.weather.proto.WeatherGridFilter getFilter() {
    return filter_ == null ? ca.wise.weather.proto.WeatherGridFilter.getDefaultInstance() : filter_;
  }
  /**
   * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
   */
  @java.lang.Override
  public ca.wise.weather.proto.WeatherGridFilterOrBuilder getFilterOrBuilder() {
    return getFilter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getCommentsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, comments_);
    }
    if (color_ != null) {
      output.writeMessage(4, getColor());
    }
    if (size_ != null) {
      output.writeMessage(5, getSize());
    }
    if (landscape_ != false) {
      output.writeBool(6, landscape_);
    }
    if (filter_ != null) {
      output.writeMessage(7, getFilter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getCommentsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, comments_);
    }
    if (color_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getColor());
    }
    if (size_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSize());
    }
    if (landscape_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, landscape_);
    }
    if (filter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getFilter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.project.proto.ProjectPolyWeatherGridFilter)) {
      return super.equals(obj);
    }
    ca.wise.project.proto.ProjectPolyWeatherGridFilter other = (ca.wise.project.proto.ProjectPolyWeatherGridFilter) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getComments()
        .equals(other.getComments())) return false;
    if (hasColor() != other.hasColor()) return false;
    if (hasColor()) {
      if (!getColor()
          .equals(other.getColor())) return false;
    }
    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (!getSize()
          .equals(other.getSize())) return false;
    }
    if (getLandscape()
        != other.getLandscape()) return false;
    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getComments().hashCode();
    if (hasColor()) {
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor().hashCode();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize().hashCode();
    }
    hash = (37 * hash) + LANDSCAPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLandscape());
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.project.proto.ProjectPolyWeatherGridFilter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.ProjectPolyWeatherGridFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.ProjectPolyWeatherGridFilter)
      ca.wise.project.proto.ProjectPolyWeatherGridFilterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.ProjectGridFilter.internal_static_WISE_ProjectProto_ProjectPolyWeatherGridFilter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.ProjectGridFilter.internal_static_WISE_ProjectProto_ProjectPolyWeatherGridFilter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.ProjectPolyWeatherGridFilter.class, ca.wise.project.proto.ProjectPolyWeatherGridFilter.Builder.class);
    }

    // Construct using ca.wise.project.proto.ProjectPolyWeatherGridFilter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      name_ = "";

      comments_ = "";

      if (colorBuilder_ == null) {
        color_ = null;
      } else {
        color_ = null;
        colorBuilder_ = null;
      }
      if (sizeBuilder_ == null) {
        size_ = null;
      } else {
        size_ = null;
        sizeBuilder_ = null;
      }
      landscape_ = false;

      if (filterBuilder_ == null) {
        filter_ = null;
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.project.proto.ProjectGridFilter.internal_static_WISE_ProjectProto_ProjectPolyWeatherGridFilter_descriptor;
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectPolyWeatherGridFilter getDefaultInstanceForType() {
      return ca.wise.project.proto.ProjectPolyWeatherGridFilter.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectPolyWeatherGridFilter build() {
      ca.wise.project.proto.ProjectPolyWeatherGridFilter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectPolyWeatherGridFilter buildPartial() {
      ca.wise.project.proto.ProjectPolyWeatherGridFilter result = new ca.wise.project.proto.ProjectPolyWeatherGridFilter(this);
      result.version_ = version_;
      result.name_ = name_;
      result.comments_ = comments_;
      if (colorBuilder_ == null) {
        result.color_ = color_;
      } else {
        result.color_ = colorBuilder_.build();
      }
      if (sizeBuilder_ == null) {
        result.size_ = size_;
      } else {
        result.size_ = sizeBuilder_.build();
      }
      result.landscape_ = landscape_;
      if (filterBuilder_ == null) {
        result.filter_ = filter_;
      } else {
        result.filter_ = filterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.project.proto.ProjectPolyWeatherGridFilter) {
        return mergeFrom((ca.wise.project.proto.ProjectPolyWeatherGridFilter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.project.proto.ProjectPolyWeatherGridFilter other) {
      if (other == ca.wise.project.proto.ProjectPolyWeatherGridFilter.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getComments().isEmpty()) {
        comments_ = other.comments_;
        onChanged();
      }
      if (other.hasColor()) {
        mergeColor(other.getColor());
      }
      if (other.hasSize()) {
        mergeSize(other.getSize());
      }
      if (other.getLandscape() != false) {
        setLandscape(other.getLandscape());
      }
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.project.proto.ProjectPolyWeatherGridFilter parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.project.proto.ProjectPolyWeatherGridFilter) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 3;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 3;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 3;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 3;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comments_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.UInt32Value color_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> colorBuilder_;
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     * @return Whether the color field is set.
     */
    public boolean hasColor() {
      return colorBuilder_ != null || color_ != null;
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     * @return The color.
     */
    public com.google.protobuf.UInt32Value getColor() {
      if (colorBuilder_ == null) {
        return color_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : color_;
      } else {
        return colorBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    public Builder setColor(com.google.protobuf.UInt32Value value) {
      if (colorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        color_ = value;
        onChanged();
      } else {
        colorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    public Builder setColor(
        com.google.protobuf.UInt32Value.Builder builderForValue) {
      if (colorBuilder_ == null) {
        color_ = builderForValue.build();
        onChanged();
      } else {
        colorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    public Builder mergeColor(com.google.protobuf.UInt32Value value) {
      if (colorBuilder_ == null) {
        if (color_ != null) {
          color_ =
            com.google.protobuf.UInt32Value.newBuilder(color_).mergeFrom(value).buildPartial();
        } else {
          color_ = value;
        }
        onChanged();
      } else {
        colorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    public Builder clearColor() {
      if (colorBuilder_ == null) {
        color_ = null;
        onChanged();
      } else {
        color_ = null;
        colorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    public com.google.protobuf.UInt32Value.Builder getColorBuilder() {
      
      onChanged();
      return getColorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    public com.google.protobuf.UInt32ValueOrBuilder getColorOrBuilder() {
      if (colorBuilder_ != null) {
        return colorBuilder_.getMessageOrBuilder();
      } else {
        return color_ == null ?
            com.google.protobuf.UInt32Value.getDefaultInstance() : color_;
      }
    }
    /**
     * <code>.google.protobuf.UInt32Value color = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> 
        getColorFieldBuilder() {
      if (colorBuilder_ == null) {
        colorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder>(
                getColor(),
                getParentForChildren(),
                isClean());
        color_ = null;
      }
      return colorBuilder_;
    }

    private com.google.protobuf.UInt64Value size_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> sizeBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     * @return Whether the size field is set.
     */
    public boolean hasSize() {
      return sizeBuilder_ != null || size_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     * @return The size.
     */
    public com.google.protobuf.UInt64Value getSize() {
      if (sizeBuilder_ == null) {
        return size_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : size_;
      } else {
        return sizeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    public Builder setSize(com.google.protobuf.UInt64Value value) {
      if (sizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        size_ = value;
        onChanged();
      } else {
        sizeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    public Builder setSize(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (sizeBuilder_ == null) {
        size_ = builderForValue.build();
        onChanged();
      } else {
        sizeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    public Builder mergeSize(com.google.protobuf.UInt64Value value) {
      if (sizeBuilder_ == null) {
        if (size_ != null) {
          size_ =
            com.google.protobuf.UInt64Value.newBuilder(size_).mergeFrom(value).buildPartial();
        } else {
          size_ = value;
        }
        onChanged();
      } else {
        sizeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    public Builder clearSize() {
      if (sizeBuilder_ == null) {
        size_ = null;
        onChanged();
      } else {
        size_ = null;
        sizeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    public com.google.protobuf.UInt64Value.Builder getSizeBuilder() {
      
      onChanged();
      return getSizeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getSizeOrBuilder() {
      if (sizeBuilder_ != null) {
        return sizeBuilder_.getMessageOrBuilder();
      } else {
        return size_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : size_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value size = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getSizeFieldBuilder() {
      if (sizeBuilder_ == null) {
        sizeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getSize(),
                getParentForChildren(),
                isClean());
        size_ = null;
      }
      return sizeBuilder_;
    }

    private boolean landscape_ ;
    /**
     * <code>bool landscape = 6;</code>
     * @return The landscape.
     */
    @java.lang.Override
    public boolean getLandscape() {
      return landscape_;
    }
    /**
     * <code>bool landscape = 6;</code>
     * @param value The landscape to set.
     * @return This builder for chaining.
     */
    public Builder setLandscape(boolean value) {
      
      landscape_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool landscape = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLandscape() {
      
      landscape_ = false;
      onChanged();
      return this;
    }

    private ca.wise.weather.proto.WeatherGridFilter filter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.weather.proto.WeatherGridFilter, ca.wise.weather.proto.WeatherGridFilter.Builder, ca.wise.weather.proto.WeatherGridFilterOrBuilder> filterBuilder_;
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return filterBuilder_ != null || filter_ != null;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     * @return The filter.
     */
    public ca.wise.weather.proto.WeatherGridFilter getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? ca.wise.weather.proto.WeatherGridFilter.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    public Builder setFilter(ca.wise.weather.proto.WeatherGridFilter value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        filterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    public Builder setFilter(
        ca.wise.weather.proto.WeatherGridFilter.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    public Builder mergeFilter(ca.wise.weather.proto.WeatherGridFilter value) {
      if (filterBuilder_ == null) {
        if (filter_ != null) {
          filter_ =
            ca.wise.weather.proto.WeatherGridFilter.newBuilder(filter_).mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        filterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    public Builder clearFilter() {
      if (filterBuilder_ == null) {
        filter_ = null;
        onChanged();
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    public ca.wise.weather.proto.WeatherGridFilter.Builder getFilterBuilder() {
      
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    public ca.wise.weather.proto.WeatherGridFilterOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            ca.wise.weather.proto.WeatherGridFilter.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>.WISE.WeatherProto.WeatherGridFilter filter = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.weather.proto.WeatherGridFilter, ca.wise.weather.proto.WeatherGridFilter.Builder, ca.wise.weather.proto.WeatherGridFilterOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.weather.proto.WeatherGridFilter, ca.wise.weather.proto.WeatherGridFilter.Builder, ca.wise.weather.proto.WeatherGridFilterOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.ProjectPolyWeatherGridFilter)
  }

  // @@protoc_insertion_point(class_scope:WISE.ProjectProto.ProjectPolyWeatherGridFilter)
  private static final ca.wise.project.proto.ProjectPolyWeatherGridFilter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.project.proto.ProjectPolyWeatherGridFilter();
  }

  public static ca.wise.project.proto.ProjectPolyWeatherGridFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProjectPolyWeatherGridFilter>
      PARSER = new com.google.protobuf.AbstractParser<ProjectPolyWeatherGridFilter>() {
    @java.lang.Override
    public ProjectPolyWeatherGridFilter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProjectPolyWeatherGridFilter(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProjectPolyWeatherGridFilter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProjectPolyWeatherGridFilter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.project.proto.ProjectPolyWeatherGridFilter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

