// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assetCollection.proto

package ca.wise.project.proto;

/**
 * Protobuf type {@code WISE.ProjectProto.ProjectAsset}
 */
@java.lang.Deprecated public final class ProjectAsset extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.ProjectProto.ProjectAsset)
    ProjectAssetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProjectAsset.newBuilder() to construct.
  private ProjectAsset(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProjectAsset() {
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProjectAsset();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProjectAsset(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            comments_ = s;
            break;
          }
          case 32: {

            color_ = input.readUInt32();
            break;
          }
          case 40: {

            fillColor_ = input.readUInt32();
            break;
          }
          case 48: {

            symbol_ = input.readUInt32();
            break;
          }
          case 56: {

            width_ = input.readSInt32();
            break;
          }
          case 64: {

            imported_ = input.readBool();
            break;
          }
          case 74: {
            ca.wise.grid.proto.CwfgmAsset.Builder subBuilder = null;
            if (dataCase_ == 9) {
              subBuilder = ((ca.wise.grid.proto.CwfgmAsset) data_).toBuilder();
            }
            data_ =
                input.readMessage(ca.wise.grid.proto.CwfgmAsset.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.grid.proto.CwfgmAsset) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 9;
            break;
          }
          case 82: {
            ca.wise.project.proto.ProjectAsset.VectorFile.Builder subBuilder = null;
            if (dataCase_ == 10) {
              subBuilder = ((ca.wise.project.proto.ProjectAsset.VectorFile) data_).toBuilder();
            }
            data_ =
                input.readMessage(ca.wise.project.proto.ProjectAsset.VectorFile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ca.wise.project.proto.ProjectAsset.VectorFile) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 10;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.project.proto.ProjectAsset.class, ca.wise.project.proto.ProjectAsset.Builder.class);
  }

  public interface VectorFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.ProjectAsset.VectorFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *The location of the file to import
     * </pre>
     *
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <pre>
     *The location of the file to import
     * </pre>
     *
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <pre>
     *The width of the fire break
     * </pre>
     *
     * <code>.Math.Double assetBoundary = 2;</code>
     * @return Whether the assetBoundary field is set.
     */
    boolean hasAssetBoundary();
    /**
     * <pre>
     *The width of the fire break
     * </pre>
     *
     * <code>.Math.Double assetBoundary = 2;</code>
     * @return The assetBoundary.
     */
    ca.hss.math.proto.Double getAssetBoundary();
    /**
     * <pre>
     *The width of the fire break
     * </pre>
     *
     * <code>.Math.Double assetBoundary = 2;</code>
     */
    ca.hss.math.proto.DoubleOrBuilder getAssetBoundaryOrBuilder();
  }
  /**
   * <pre>
   **
   * Information for a file to import as a fire break.
   * </pre>
   *
   * Protobuf type {@code WISE.ProjectProto.ProjectAsset.VectorFile}
   */
  public static final class VectorFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.ProjectProto.ProjectAsset.VectorFile)
      VectorFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VectorFile.newBuilder() to construct.
    private VectorFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VectorFile() {
      filename_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VectorFile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VectorFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 18: {
              ca.hss.math.proto.Double.Builder subBuilder = null;
              if (assetBoundary_ != null) {
                subBuilder = assetBoundary_.toBuilder();
              }
              assetBoundary_ = input.readMessage(ca.hss.math.proto.Double.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(assetBoundary_);
                assetBoundary_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_VectorFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_VectorFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.ProjectAsset.VectorFile.class, ca.wise.project.proto.ProjectAsset.VectorFile.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object filename_;
    /**
     * <pre>
     *The location of the file to import
     * </pre>
     *
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *The location of the file to import
     * </pre>
     *
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSETBOUNDARY_FIELD_NUMBER = 2;
    private ca.hss.math.proto.Double assetBoundary_;
    /**
     * <pre>
     *The width of the fire break
     * </pre>
     *
     * <code>.Math.Double assetBoundary = 2;</code>
     * @return Whether the assetBoundary field is set.
     */
    @java.lang.Override
    public boolean hasAssetBoundary() {
      return assetBoundary_ != null;
    }
    /**
     * <pre>
     *The width of the fire break
     * </pre>
     *
     * <code>.Math.Double assetBoundary = 2;</code>
     * @return The assetBoundary.
     */
    @java.lang.Override
    public ca.hss.math.proto.Double getAssetBoundary() {
      return assetBoundary_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : assetBoundary_;
    }
    /**
     * <pre>
     *The width of the fire break
     * </pre>
     *
     * <code>.Math.Double assetBoundary = 2;</code>
     */
    @java.lang.Override
    public ca.hss.math.proto.DoubleOrBuilder getAssetBoundaryOrBuilder() {
      return getAssetBoundary();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (assetBoundary_ != null) {
        output.writeMessage(2, getAssetBoundary());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (assetBoundary_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAssetBoundary());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.project.proto.ProjectAsset.VectorFile)) {
        return super.equals(obj);
      }
      ca.wise.project.proto.ProjectAsset.VectorFile other = (ca.wise.project.proto.ProjectAsset.VectorFile) obj;

      if (!getFilename()
          .equals(other.getFilename())) return false;
      if (hasAssetBoundary() != other.hasAssetBoundary()) return false;
      if (hasAssetBoundary()) {
        if (!getAssetBoundary()
            .equals(other.getAssetBoundary())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      if (hasAssetBoundary()) {
        hash = (37 * hash) + ASSETBOUNDARY_FIELD_NUMBER;
        hash = (53 * hash) + getAssetBoundary().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.project.proto.ProjectAsset.VectorFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.project.proto.ProjectAsset.VectorFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Information for a file to import as a fire break.
     * </pre>
     *
     * Protobuf type {@code WISE.ProjectProto.ProjectAsset.VectorFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.ProjectAsset.VectorFile)
        ca.wise.project.proto.ProjectAsset.VectorFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_VectorFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_VectorFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.project.proto.ProjectAsset.VectorFile.class, ca.wise.project.proto.ProjectAsset.VectorFile.Builder.class);
      }

      // Construct using ca.wise.project.proto.ProjectAsset.VectorFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        filename_ = "";

        if (assetBoundaryBuilder_ == null) {
          assetBoundary_ = null;
        } else {
          assetBoundary_ = null;
          assetBoundaryBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_VectorFile_descriptor;
      }

      @java.lang.Override
      public ca.wise.project.proto.ProjectAsset.VectorFile getDefaultInstanceForType() {
        return ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.project.proto.ProjectAsset.VectorFile build() {
        ca.wise.project.proto.ProjectAsset.VectorFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.project.proto.ProjectAsset.VectorFile buildPartial() {
        ca.wise.project.proto.ProjectAsset.VectorFile result = new ca.wise.project.proto.ProjectAsset.VectorFile(this);
        result.filename_ = filename_;
        if (assetBoundaryBuilder_ == null) {
          result.assetBoundary_ = assetBoundary_;
        } else {
          result.assetBoundary_ = assetBoundaryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.project.proto.ProjectAsset.VectorFile) {
          return mergeFrom((ca.wise.project.proto.ProjectAsset.VectorFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.project.proto.ProjectAsset.VectorFile other) {
        if (other == ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance()) return this;
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        if (other.hasAssetBoundary()) {
          mergeAssetBoundary(other.getAssetBoundary());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.project.proto.ProjectAsset.VectorFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.project.proto.ProjectAsset.VectorFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <pre>
       *The location of the file to import
       * </pre>
       *
       * <code>string filename = 1;</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *The location of the file to import
       * </pre>
       *
       * <code>string filename = 1;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *The location of the file to import
       * </pre>
       *
       * <code>string filename = 1;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The location of the file to import
       * </pre>
       *
       * <code>string filename = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The location of the file to import
       * </pre>
       *
       * <code>string filename = 1;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private ca.hss.math.proto.Double assetBoundary_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> assetBoundaryBuilder_;
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       * @return Whether the assetBoundary field is set.
       */
      public boolean hasAssetBoundary() {
        return assetBoundaryBuilder_ != null || assetBoundary_ != null;
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       * @return The assetBoundary.
       */
      public ca.hss.math.proto.Double getAssetBoundary() {
        if (assetBoundaryBuilder_ == null) {
          return assetBoundary_ == null ? ca.hss.math.proto.Double.getDefaultInstance() : assetBoundary_;
        } else {
          return assetBoundaryBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      public Builder setAssetBoundary(ca.hss.math.proto.Double value) {
        if (assetBoundaryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          assetBoundary_ = value;
          onChanged();
        } else {
          assetBoundaryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      public Builder setAssetBoundary(
          ca.hss.math.proto.Double.Builder builderForValue) {
        if (assetBoundaryBuilder_ == null) {
          assetBoundary_ = builderForValue.build();
          onChanged();
        } else {
          assetBoundaryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      public Builder mergeAssetBoundary(ca.hss.math.proto.Double value) {
        if (assetBoundaryBuilder_ == null) {
          if (assetBoundary_ != null) {
            assetBoundary_ =
              ca.hss.math.proto.Double.newBuilder(assetBoundary_).mergeFrom(value).buildPartial();
          } else {
            assetBoundary_ = value;
          }
          onChanged();
        } else {
          assetBoundaryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      public Builder clearAssetBoundary() {
        if (assetBoundaryBuilder_ == null) {
          assetBoundary_ = null;
          onChanged();
        } else {
          assetBoundary_ = null;
          assetBoundaryBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      public ca.hss.math.proto.Double.Builder getAssetBoundaryBuilder() {
        
        onChanged();
        return getAssetBoundaryFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      public ca.hss.math.proto.DoubleOrBuilder getAssetBoundaryOrBuilder() {
        if (assetBoundaryBuilder_ != null) {
          return assetBoundaryBuilder_.getMessageOrBuilder();
        } else {
          return assetBoundary_ == null ?
              ca.hss.math.proto.Double.getDefaultInstance() : assetBoundary_;
        }
      }
      /**
       * <pre>
       *The width of the fire break
       * </pre>
       *
       * <code>.Math.Double assetBoundary = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder> 
          getAssetBoundaryFieldBuilder() {
        if (assetBoundaryBuilder_ == null) {
          assetBoundaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.hss.math.proto.Double, ca.hss.math.proto.Double.Builder, ca.hss.math.proto.DoubleOrBuilder>(
                  getAssetBoundary(),
                  getParentForChildren(),
                  isClean());
          assetBoundary_ = null;
        }
        return assetBoundaryBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.ProjectAsset.VectorFile)
    }

    // @@protoc_insertion_point(class_scope:WISE.ProjectProto.ProjectAsset.VectorFile)
    private static final ca.wise.project.proto.ProjectAsset.VectorFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.project.proto.ProjectAsset.VectorFile();
    }

    public static ca.wise.project.proto.ProjectAsset.VectorFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VectorFile>
        PARSER = new com.google.protobuf.AbstractParser<VectorFile>() {
      @java.lang.Override
      public VectorFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VectorFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VectorFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VectorFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectAsset.VectorFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILTER(9),
    FILE(10),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 9: return FILTER;
        case 10: return FILE;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 3;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 3;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 3;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private int color_;
  /**
   * <code>uint32 color = 4;</code>
   * @return The color.
   */
  @java.lang.Override
  public int getColor() {
    return color_;
  }

  public static final int FILLCOLOR_FIELD_NUMBER = 5;
  private int fillColor_;
  /**
   * <code>uint32 fillColor = 5;</code>
   * @return The fillColor.
   */
  @java.lang.Override
  public int getFillColor() {
    return fillColor_;
  }

  public static final int SYMBOL_FIELD_NUMBER = 6;
  private int symbol_;
  /**
   * <code>uint32 symbol = 6;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public int getSymbol() {
    return symbol_;
  }

  public static final int WIDTH_FIELD_NUMBER = 7;
  private int width_;
  /**
   * <code>sint32 width = 7;</code>
   * @return The width.
   */
  @java.lang.Override
  public int getWidth() {
    return width_;
  }

  public static final int IMPORTED_FIELD_NUMBER = 8;
  private boolean imported_;
  /**
   * <code>bool imported = 8;</code>
   * @return The imported.
   */
  @java.lang.Override
  public boolean getImported() {
    return imported_;
  }

  public static final int FILTER_FIELD_NUMBER = 9;
  /**
   * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return dataCase_ == 9;
  }
  /**
   * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
   * @return The filter.
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmAsset getFilter() {
    if (dataCase_ == 9) {
       return (ca.wise.grid.proto.CwfgmAsset) data_;
    }
    return ca.wise.grid.proto.CwfgmAsset.getDefaultInstance();
  }
  /**
   * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmAssetOrBuilder getFilterOrBuilder() {
    if (dataCase_ == 9) {
       return (ca.wise.grid.proto.CwfgmAsset) data_;
    }
    return ca.wise.grid.proto.CwfgmAsset.getDefaultInstance();
  }

  public static final int FILE_FIELD_NUMBER = 10;
  /**
   * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return dataCase_ == 10;
  }
  /**
   * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
   * @return The file.
   */
  @java.lang.Override
  public ca.wise.project.proto.ProjectAsset.VectorFile getFile() {
    if (dataCase_ == 10) {
       return (ca.wise.project.proto.ProjectAsset.VectorFile) data_;
    }
    return ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
  }
  /**
   * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
   */
  @java.lang.Override
  public ca.wise.project.proto.ProjectAsset.VectorFileOrBuilder getFileOrBuilder() {
    if (dataCase_ == 10) {
       return (ca.wise.project.proto.ProjectAsset.VectorFile) data_;
    }
    return ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getCommentsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, comments_);
    }
    if (color_ != 0) {
      output.writeUInt32(4, color_);
    }
    if (fillColor_ != 0) {
      output.writeUInt32(5, fillColor_);
    }
    if (symbol_ != 0) {
      output.writeUInt32(6, symbol_);
    }
    if (width_ != 0) {
      output.writeSInt32(7, width_);
    }
    if (imported_ != false) {
      output.writeBool(8, imported_);
    }
    if (dataCase_ == 9) {
      output.writeMessage(9, (ca.wise.grid.proto.CwfgmAsset) data_);
    }
    if (dataCase_ == 10) {
      output.writeMessage(10, (ca.wise.project.proto.ProjectAsset.VectorFile) data_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getCommentsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, comments_);
    }
    if (color_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, color_);
    }
    if (fillColor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, fillColor_);
    }
    if (symbol_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, symbol_);
    }
    if (width_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(7, width_);
    }
    if (imported_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, imported_);
    }
    if (dataCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (ca.wise.grid.proto.CwfgmAsset) data_);
    }
    if (dataCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (ca.wise.project.proto.ProjectAsset.VectorFile) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.project.proto.ProjectAsset)) {
      return super.equals(obj);
    }
    ca.wise.project.proto.ProjectAsset other = (ca.wise.project.proto.ProjectAsset) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getComments()
        .equals(other.getComments())) return false;
    if (getColor()
        != other.getColor()) return false;
    if (getFillColor()
        != other.getFillColor()) return false;
    if (getSymbol()
        != other.getSymbol()) return false;
    if (getWidth()
        != other.getWidth()) return false;
    if (getImported()
        != other.getImported()) return false;
    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 9:
        if (!getFilter()
            .equals(other.getFilter())) return false;
        break;
      case 10:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getComments().hashCode();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor();
    hash = (37 * hash) + FILLCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getFillColor();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol();
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getWidth();
    hash = (37 * hash) + IMPORTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImported());
    switch (dataCase_) {
      case 9:
        hash = (37 * hash) + FILTER_FIELD_NUMBER;
        hash = (53 * hash) + getFilter().hashCode();
        break;
      case 10:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.project.proto.ProjectAsset parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectAsset parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.ProjectAsset parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.ProjectAsset parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.project.proto.ProjectAsset prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.ProjectAsset}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.ProjectAsset)
      ca.wise.project.proto.ProjectAssetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.ProjectAsset.class, ca.wise.project.proto.ProjectAsset.Builder.class);
    }

    // Construct using ca.wise.project.proto.ProjectAsset.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      name_ = "";

      comments_ = "";

      color_ = 0;

      fillColor_ = 0;

      symbol_ = 0;

      width_ = 0;

      imported_ = false;

      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.project.proto.AssetCollectionOuterClass.internal_static_WISE_ProjectProto_ProjectAsset_descriptor;
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectAsset getDefaultInstanceForType() {
      return ca.wise.project.proto.ProjectAsset.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectAsset build() {
      ca.wise.project.proto.ProjectAsset result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.project.proto.ProjectAsset buildPartial() {
      ca.wise.project.proto.ProjectAsset result = new ca.wise.project.proto.ProjectAsset(this);
      result.version_ = version_;
      result.name_ = name_;
      result.comments_ = comments_;
      result.color_ = color_;
      result.fillColor_ = fillColor_;
      result.symbol_ = symbol_;
      result.width_ = width_;
      result.imported_ = imported_;
      if (dataCase_ == 9) {
        if (filterBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = filterBuilder_.build();
        }
      }
      if (dataCase_ == 10) {
        if (fileBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = fileBuilder_.build();
        }
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.project.proto.ProjectAsset) {
        return mergeFrom((ca.wise.project.proto.ProjectAsset)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.project.proto.ProjectAsset other) {
      if (other == ca.wise.project.proto.ProjectAsset.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getComments().isEmpty()) {
        comments_ = other.comments_;
        onChanged();
      }
      if (other.getColor() != 0) {
        setColor(other.getColor());
      }
      if (other.getFillColor() != 0) {
        setFillColor(other.getFillColor());
      }
      if (other.getSymbol() != 0) {
        setSymbol(other.getSymbol());
      }
      if (other.getWidth() != 0) {
        setWidth(other.getWidth());
      }
      if (other.getImported() != false) {
        setImported(other.getImported());
      }
      switch (other.getDataCase()) {
        case FILTER: {
          mergeFilter(other.getFilter());
          break;
        }
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.project.proto.ProjectAsset parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.project.proto.ProjectAsset) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 3;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 3;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 3;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 3;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comments_ = value;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>uint32 color = 4;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }
    /**
     * <code>uint32 color = 4;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {
      
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 color = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      
      color_ = 0;
      onChanged();
      return this;
    }

    private int fillColor_ ;
    /**
     * <code>uint32 fillColor = 5;</code>
     * @return The fillColor.
     */
    @java.lang.Override
    public int getFillColor() {
      return fillColor_;
    }
    /**
     * <code>uint32 fillColor = 5;</code>
     * @param value The fillColor to set.
     * @return This builder for chaining.
     */
    public Builder setFillColor(int value) {
      
      fillColor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 fillColor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFillColor() {
      
      fillColor_ = 0;
      onChanged();
      return this;
    }

    private int symbol_ ;
    /**
     * <code>uint32 symbol = 6;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public int getSymbol() {
      return symbol_;
    }
    /**
     * <code>uint32 symbol = 6;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(int value) {
      
      symbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 symbol = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      
      symbol_ = 0;
      onChanged();
      return this;
    }

    private int width_ ;
    /**
     * <code>sint32 width = 7;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }
    /**
     * <code>sint32 width = 7;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(int value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 width = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      
      width_ = 0;
      onChanged();
      return this;
    }

    private boolean imported_ ;
    /**
     * <code>bool imported = 8;</code>
     * @return The imported.
     */
    @java.lang.Override
    public boolean getImported() {
      return imported_;
    }
    /**
     * <code>bool imported = 8;</code>
     * @param value The imported to set.
     * @return This builder for chaining.
     */
    public Builder setImported(boolean value) {
      
      imported_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool imported = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearImported() {
      
      imported_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmAsset, ca.wise.grid.proto.CwfgmAsset.Builder, ca.wise.grid.proto.CwfgmAssetOrBuilder> filterBuilder_;
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     * @return Whether the filter field is set.
     */
    @java.lang.Override
    public boolean hasFilter() {
      return dataCase_ == 9;
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     * @return The filter.
     */
    @java.lang.Override
    public ca.wise.grid.proto.CwfgmAsset getFilter() {
      if (filterBuilder_ == null) {
        if (dataCase_ == 9) {
          return (ca.wise.grid.proto.CwfgmAsset) data_;
        }
        return ca.wise.grid.proto.CwfgmAsset.getDefaultInstance();
      } else {
        if (dataCase_ == 9) {
          return filterBuilder_.getMessage();
        }
        return ca.wise.grid.proto.CwfgmAsset.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    public Builder setFilter(ca.wise.grid.proto.CwfgmAsset value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        filterBuilder_.setMessage(value);
      }
      dataCase_ = 9;
      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    public Builder setFilter(
        ca.wise.grid.proto.CwfgmAsset.Builder builderForValue) {
      if (filterBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 9;
      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    public Builder mergeFilter(ca.wise.grid.proto.CwfgmAsset value) {
      if (filterBuilder_ == null) {
        if (dataCase_ == 9 &&
            data_ != ca.wise.grid.proto.CwfgmAsset.getDefaultInstance()) {
          data_ = ca.wise.grid.proto.CwfgmAsset.newBuilder((ca.wise.grid.proto.CwfgmAsset) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 9) {
          filterBuilder_.mergeFrom(value);
        }
        filterBuilder_.setMessage(value);
      }
      dataCase_ = 9;
      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    public Builder clearFilter() {
      if (filterBuilder_ == null) {
        if (dataCase_ == 9) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 9) {
          dataCase_ = 0;
          data_ = null;
        }
        filterBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    public ca.wise.grid.proto.CwfgmAsset.Builder getFilterBuilder() {
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    @java.lang.Override
    public ca.wise.grid.proto.CwfgmAssetOrBuilder getFilterOrBuilder() {
      if ((dataCase_ == 9) && (filterBuilder_ != null)) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 9) {
          return (ca.wise.grid.proto.CwfgmAsset) data_;
        }
        return ca.wise.grid.proto.CwfgmAsset.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmAsset filter = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmAsset, ca.wise.grid.proto.CwfgmAsset.Builder, ca.wise.grid.proto.CwfgmAssetOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        if (!(dataCase_ == 9)) {
          data_ = ca.wise.grid.proto.CwfgmAsset.getDefaultInstance();
        }
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.grid.proto.CwfgmAsset, ca.wise.grid.proto.CwfgmAsset.Builder, ca.wise.grid.proto.CwfgmAssetOrBuilder>(
                (ca.wise.grid.proto.CwfgmAsset) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 9;
      onChanged();;
      return filterBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.project.proto.ProjectAsset.VectorFile, ca.wise.project.proto.ProjectAsset.VectorFile.Builder, ca.wise.project.proto.ProjectAsset.VectorFileOrBuilder> fileBuilder_;
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return dataCase_ == 10;
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     * @return The file.
     */
    @java.lang.Override
    public ca.wise.project.proto.ProjectAsset.VectorFile getFile() {
      if (fileBuilder_ == null) {
        if (dataCase_ == 10) {
          return (ca.wise.project.proto.ProjectAsset.VectorFile) data_;
        }
        return ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
      } else {
        if (dataCase_ == 10) {
          return fileBuilder_.getMessage();
        }
        return ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    public Builder setFile(ca.wise.project.proto.ProjectAsset.VectorFile value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      dataCase_ = 10;
      return this;
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    public Builder setFile(
        ca.wise.project.proto.ProjectAsset.VectorFile.Builder builderForValue) {
      if (fileBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 10;
      return this;
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    public Builder mergeFile(ca.wise.project.proto.ProjectAsset.VectorFile value) {
      if (fileBuilder_ == null) {
        if (dataCase_ == 10 &&
            data_ != ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance()) {
          data_ = ca.wise.project.proto.ProjectAsset.VectorFile.newBuilder((ca.wise.project.proto.ProjectAsset.VectorFile) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 10) {
          fileBuilder_.mergeFrom(value);
        }
        fileBuilder_.setMessage(value);
      }
      dataCase_ = 10;
      return this;
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (dataCase_ == 10) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 10) {
          dataCase_ = 0;
          data_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    public ca.wise.project.proto.ProjectAsset.VectorFile.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    @java.lang.Override
    public ca.wise.project.proto.ProjectAsset.VectorFileOrBuilder getFileOrBuilder() {
      if ((dataCase_ == 10) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 10) {
          return (ca.wise.project.proto.ProjectAsset.VectorFile) data_;
        }
        return ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
      }
    }
    /**
     * <code>.WISE.ProjectProto.ProjectAsset.VectorFile file = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.project.proto.ProjectAsset.VectorFile, ca.wise.project.proto.ProjectAsset.VectorFile.Builder, ca.wise.project.proto.ProjectAsset.VectorFileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(dataCase_ == 10)) {
          data_ = ca.wise.project.proto.ProjectAsset.VectorFile.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.project.proto.ProjectAsset.VectorFile, ca.wise.project.proto.ProjectAsset.VectorFile.Builder, ca.wise.project.proto.ProjectAsset.VectorFileOrBuilder>(
                (ca.wise.project.proto.ProjectAsset.VectorFile) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 10;
      onChanged();;
      return fileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.ProjectAsset)
  }

  // @@protoc_insertion_point(class_scope:WISE.ProjectProto.ProjectAsset)
  private static final ca.wise.project.proto.ProjectAsset DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.project.proto.ProjectAsset();
  }

  public static ca.wise.project.proto.ProjectAsset getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProjectAsset>
      PARSER = new com.google.protobuf.AbstractParser<ProjectAsset>() {
    @java.lang.Override
    public ProjectAsset parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProjectAsset(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProjectAsset> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProjectAsset> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.project.proto.ProjectAsset getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

