// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectWindGrid.proto

package ca.wise.project.proto;

@java.lang.Deprecated public interface ProjectWindGridOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.ProjectWindGrid)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 3;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 3;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>.WISE.WeatherProto.WindGrid.GridType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.WISE.WeatherProto.WindGrid.GridType type = 4;</code>
   * @return The type.
   */
  ca.wise.weather.proto.WindGrid.GridType getType();

  /**
   * <code>.WISE.WeatherProto.WindGrid grid = 5;</code>
   * @return Whether the grid field is set.
   */
  boolean hasGrid();
  /**
   * <code>.WISE.WeatherProto.WindGrid grid = 5;</code>
   * @return The grid.
   */
  ca.wise.weather.proto.WindGrid getGrid();
  /**
   * <code>.WISE.WeatherProto.WindGrid grid = 5;</code>
   */
  ca.wise.weather.proto.WindGridOrBuilder getGridOrBuilder();
}
