// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assetCollection.proto

package ca.wise.project.proto;

@java.lang.Deprecated public interface ProjectTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.ProjectTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 3;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 3;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 4;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint32 symbol = 5;</code>
   * @return The symbol.
   */
  int getSymbol();

  /**
   * <code>sint32 displaySize = 6;</code>
   * @return The displaySize.
   */
  int getDisplaySize();

  /**
   * <code>bool imported = 7;</code>
   * @return The imported.
   */
  boolean getImported();

  /**
   * <code>.WISE.GridProto.CwfgmTarget filter = 8;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.WISE.GridProto.CwfgmTarget filter = 8;</code>
   * @return The filter.
   */
  ca.wise.grid.proto.CwfgmTarget getFilter();
  /**
   * <code>.WISE.GridProto.CwfgmTarget filter = 8;</code>
   */
  ca.wise.grid.proto.CwfgmTargetOrBuilder getFilterOrBuilder();

  /**
   * <code>.WISE.ProjectProto.ProjectTarget.TargetFile file = 9;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.WISE.ProjectProto.ProjectTarget.TargetFile file = 9;</code>
   * @return The file.
   */
  ca.wise.project.proto.ProjectTarget.TargetFile getFile();
  /**
   * <code>.WISE.ProjectProto.ProjectTarget.TargetFile file = 9;</code>
   */
  ca.wise.project.proto.ProjectTarget.TargetFileOrBuilder getFileOrBuilder();

  public ca.wise.project.proto.ProjectTarget.DataCase getDataCase();
}
