// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectGridFilter.proto

package ca.wise.project.proto;

@java.lang.Deprecated public interface ProjectReplaceGridFilterBaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.ProjectReplaceGridFilterBase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>int32 toFuelIndex = 2;</code>
   * @return The toFuelIndex.
   */
  int getToFuelIndex();

  /**
   * <code>string toFuelName = 3;</code>
   * @return The toFuelName.
   */
  java.lang.String getToFuelName();
  /**
   * <code>string toFuelName = 3;</code>
   * @return The bytes for toFuelName.
   */
  com.google.protobuf.ByteString
      getToFuelNameBytes();

  /**
   * <code>int32 fromFuelIndex = 4;</code>
   * @return The fromFuelIndex.
   */
  int getFromFuelIndex();

  /**
   * <code>string fromFuelName = 5;</code>
   * @return The fromFuelName.
   */
  java.lang.String getFromFuelName();
  /**
   * <code>string fromFuelName = 5;</code>
   * @return The bytes for fromFuelName.
   */
  com.google.protobuf.ByteString
      getFromFuelNameBytes();

  /**
   * <code>.WISE.ProjectProto.ProjectReplaceGridFilterBase.FromFuelRule fromFuelRule = 6;</code>
   * @return The enum numeric value on the wire for fromFuelRule.
   */
  int getFromFuelRuleValue();
  /**
   * <code>.WISE.ProjectProto.ProjectReplaceGridFilterBase.FromFuelRule fromFuelRule = 6;</code>
   * @return The fromFuelRule.
   */
  ca.wise.project.proto.ProjectReplaceGridFilterBase.FromFuelRule getFromFuelRule();

  public ca.wise.project.proto.ProjectReplaceGridFilterBase.ToFuelCase getToFuelCase();

  public ca.wise.project.proto.ProjectReplaceGridFilterBase.FromFuelCase getFromFuelCase();
}
