// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package ca.wise.project.proto;

public interface ScenarioReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.ScenarioReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Did the user request the application settings in the output
   * </pre>
   *
   * <code>bool output_application_settings = 1;</code>
   * @return The outputApplicationSettings.
   */
  boolean getOutputApplicationSettings();

  /**
   * <pre>
   *Did the user request the scenario settings in the output
   * </pre>
   *
   * <code>bool output_scenario_settings = 2;</code>
   * @return The outputScenarioSettings.
   */
  boolean getOutputScenarioSettings();

  /**
   * <pre>
   *Did the user request the landscape properties in the output
   * </pre>
   *
   * <code>bool output_landscape_properties = 3;</code>
   * @return The outputLandscapeProperties.
   */
  boolean getOutputLandscapeProperties();

  /**
   * <pre>
   *Did the user request the input files in the output
   * </pre>
   *
   * <code>bool output_input_files = 4;</code>
   * @return The outputInputFiles.
   */
  boolean getOutputInputFiles();

  /**
   * <pre>
   *Did the user request the fuel patches in the output
   * </pre>
   *
   * <code>bool output_fuel_patches = 5;</code>
   * @return The outputFuelPatches.
   */
  boolean getOutputFuelPatches();

  /**
   * <pre>
   *Did the user request the weather patches/grids in the output
   * </pre>
   *
   * <code>bool output_weather_patches_grids = 6;</code>
   * @return The outputWeatherPatchesGrids.
   */
  boolean getOutputWeatherPatchesGrids();

  /**
   * <pre>
   *Did the user request the geo-location data in the output
   * </pre>
   *
   * <code>bool output_geo_data = 7;</code>
   * @return The outputGeoData.
   */
  boolean getOutputGeoData();

  /**
   * <pre>
   *Did the user request the ignitions in the output
   * </pre>
   *
   * <code>bool output_ignitions = 8;</code>
   * @return The outputIgnitions.
   */
  boolean getOutputIgnitions();

  /**
   * <pre>
   *Did the user request the weather streams in the output
   * </pre>
   *
   * <code>bool output_weather_streams = 9;</code>
   * @return The outputWeatherStreams.
   */
  boolean getOutputWeatherStreams();

  /**
   * <pre>
   *Did the user request the fuel types in the output
   * </pre>
   *
   * <code>bool output_fuel_types = 10;</code>
   * @return The outputFuelTypes.
   */
  boolean getOutputFuelTypes();

  /**
   * <pre>
   *Did the user request the scenario comments in the output
   * </pre>
   *
   * <code>bool output_scenario_comments = 11;</code>
   * @return The outputScenarioComments.
   */
  boolean getOutputScenarioComments();

  /**
   * <pre>
   *The name of the FGM file that is being run
   * </pre>
   *
   * <code>.google.protobuf.StringValue fgm_name = 12;</code>
   * @return Whether the fgmName field is set.
   */
  boolean hasFgmName();
  /**
   * <pre>
   *The name of the FGM file that is being run
   * </pre>
   *
   * <code>.google.protobuf.StringValue fgm_name = 12;</code>
   * @return The fgmName.
   */
  com.google.protobuf.StringValue getFgmName();
  /**
   * <pre>
   *The name of the FGM file that is being run
   * </pre>
   *
   * <code>.google.protobuf.StringValue fgm_name = 12;</code>
   */
  com.google.protobuf.StringValueOrBuilder getFgmNameOrBuilder();

  /**
   * <pre>
   *The date that the report was generated on
   * </pre>
   *
   * <code>string report_date = 13;</code>
   * @return The reportDate.
   */
  java.lang.String getReportDate();
  /**
   * <pre>
   *The date that the report was generated on
   * </pre>
   *
   * <code>string report_date = 13;</code>
   * @return The bytes for reportDate.
   */
  com.google.protobuf.ByteString
      getReportDateBytes();

  /**
   * <pre>
   *The name of the scenario that the report is for
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_name = 14;</code>
   * @return Whether the scenarioName field is set.
   */
  boolean hasScenarioName();
  /**
   * <pre>
   *The name of the scenario that the report is for
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_name = 14;</code>
   * @return The scenarioName.
   */
  com.google.protobuf.StringValue getScenarioName();
  /**
   * <pre>
   *The name of the scenario that the report is for
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_name = 14;</code>
   */
  com.google.protobuf.StringValueOrBuilder getScenarioNameOrBuilder();

  /**
   * <pre>
   *The start time of the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_start = 15;</code>
   * @return Whether the scenarioStart field is set.
   */
  boolean hasScenarioStart();
  /**
   * <pre>
   *The start time of the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_start = 15;</code>
   * @return The scenarioStart.
   */
  com.google.protobuf.StringValue getScenarioStart();
  /**
   * <pre>
   *The start time of the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_start = 15;</code>
   */
  com.google.protobuf.StringValueOrBuilder getScenarioStartOrBuilder();

  /**
   * <pre>
   *The end time of the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_end = 16;</code>
   * @return Whether the scenarioEnd field is set.
   */
  boolean hasScenarioEnd();
  /**
   * <pre>
   *The end time of the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_end = 16;</code>
   * @return The scenarioEnd.
   */
  com.google.protobuf.StringValue getScenarioEnd();
  /**
   * <pre>
   *The end time of the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_end = 16;</code>
   */
  com.google.protobuf.StringValueOrBuilder getScenarioEndOrBuilder();

  /**
   * <pre>
   *A list of ignitions that are attached to the scenario
   * </pre>
   *
   * <code>repeated string ignition_ref = 17;</code>
   * @return A list containing the ignitionRef.
   */
  java.util.List<java.lang.String>
      getIgnitionRefList();
  /**
   * <pre>
   *A list of ignitions that are attached to the scenario
   * </pre>
   *
   * <code>repeated string ignition_ref = 17;</code>
   * @return The count of ignitionRef.
   */
  int getIgnitionRefCount();
  /**
   * <pre>
   *A list of ignitions that are attached to the scenario
   * </pre>
   *
   * <code>repeated string ignition_ref = 17;</code>
   * @param index The index of the element to return.
   * @return The ignitionRef at the given index.
   */
  java.lang.String getIgnitionRef(int index);
  /**
   * <pre>
   *A list of ignitions that are attached to the scenario
   * </pre>
   *
   * <code>repeated string ignition_ref = 17;</code>
   * @param index The index of the value to return.
   * @return The bytes of the ignitionRef at the given index.
   */
  com.google.protobuf.ByteString
      getIgnitionRefBytes(int index);

  /**
   * <pre>
   *A list of fuel breaks used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelBreak fuel_breaks = 18;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.FuelBreak> 
      getFuelBreaksList();
  /**
   * <pre>
   *A list of fuel breaks used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelBreak fuel_breaks = 18;</code>
   */
  ca.wise.project.proto.ScenarioReport.FuelBreak getFuelBreaks(int index);
  /**
   * <pre>
   *A list of fuel breaks used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelBreak fuel_breaks = 18;</code>
   */
  int getFuelBreaksCount();
  /**
   * <pre>
   *A list of fuel breaks used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelBreak fuel_breaks = 18;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.FuelBreakOrBuilder> 
      getFuelBreaksOrBuilderList();
  /**
   * <pre>
   *A list of fuel breaks used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelBreak fuel_breaks = 18;</code>
   */
  ca.wise.project.proto.ScenarioReport.FuelBreakOrBuilder getFuelBreaksOrBuilder(
      int index);

  /**
   * <pre>
   *A list of grid filters that are used by the scenario
   * </pre>
   *
   * <code>repeated string grid_filter_ref = 19;</code>
   * @return A list containing the gridFilterRef.
   */
  java.util.List<java.lang.String>
      getGridFilterRefList();
  /**
   * <pre>
   *A list of grid filters that are used by the scenario
   * </pre>
   *
   * <code>repeated string grid_filter_ref = 19;</code>
   * @return The count of gridFilterRef.
   */
  int getGridFilterRefCount();
  /**
   * <pre>
   *A list of grid filters that are used by the scenario
   * </pre>
   *
   * <code>repeated string grid_filter_ref = 19;</code>
   * @param index The index of the element to return.
   * @return The gridFilterRef at the given index.
   */
  java.lang.String getGridFilterRef(int index);
  /**
   * <pre>
   *A list of grid filters that are used by the scenario
   * </pre>
   *
   * <code>repeated string grid_filter_ref = 19;</code>
   * @param index The index of the value to return.
   * @return The bytes of the gridFilterRef at the given index.
   */
  com.google.protobuf.ByteString
      getGridFilterRefBytes(int index);

  /**
   * <pre>
   *A list of weather streams that are used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherStream weather_streams = 20;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.WeatherStream> 
      getWeatherStreamsList();
  /**
   * <pre>
   *A list of weather streams that are used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherStream weather_streams = 20;</code>
   */
  ca.wise.project.proto.ScenarioReport.WeatherStream getWeatherStreams(int index);
  /**
   * <pre>
   *A list of weather streams that are used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherStream weather_streams = 20;</code>
   */
  int getWeatherStreamsCount();
  /**
   * <pre>
   *A list of weather streams that are used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherStream weather_streams = 20;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.WeatherStreamOrBuilder> 
      getWeatherStreamsOrBuilderList();
  /**
   * <pre>
   *A list of weather streams that are used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherStream weather_streams = 20;</code>
   */
  ca.wise.project.proto.ScenarioReport.WeatherStreamOrBuilder getWeatherStreamsOrBuilder(
      int index);

  /**
   * <pre>
   *The user comment on the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_comment = 21;</code>
   * @return Whether the scenarioComment field is set.
   */
  boolean hasScenarioComment();
  /**
   * <pre>
   *The user comment on the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_comment = 21;</code>
   * @return The scenarioComment.
   */
  com.google.protobuf.StringValue getScenarioComment();
  /**
   * <pre>
   *The user comment on the scenario
   * </pre>
   *
   * <code>.google.protobuf.StringValue scenario_comment = 21;</code>
   */
  com.google.protobuf.StringValueOrBuilder getScenarioCommentOrBuilder();

  /**
   * <pre>
   *Burning conditions
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.BurnCondition burn_conditions = 22;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.BurnCondition> 
      getBurnConditionsList();
  /**
   * <pre>
   *Burning conditions
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.BurnCondition burn_conditions = 22;</code>
   */
  ca.wise.project.proto.ScenarioReport.BurnCondition getBurnConditions(int index);
  /**
   * <pre>
   *Burning conditions
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.BurnCondition burn_conditions = 22;</code>
   */
  int getBurnConditionsCount();
  /**
   * <pre>
   *Burning conditions
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.BurnCondition burn_conditions = 22;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.BurnConditionOrBuilder> 
      getBurnConditionsOrBuilderList();
  /**
   * <pre>
   *Burning conditions
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.BurnCondition burn_conditions = 22;</code>
   */
  ca.wise.project.proto.ScenarioReport.BurnConditionOrBuilder getBurnConditionsOrBuilder(
      int index);

  /**
   * <code>.WISE.ProjectProto.ScenarioReport.WeatherInterpMethod weather_spatial_interp = 23;</code>
   * @return The enum numeric value on the wire for weatherSpatialInterp.
   */
  int getWeatherSpatialInterpValue();
  /**
   * <code>.WISE.ProjectProto.ScenarioReport.WeatherInterpMethod weather_spatial_interp = 23;</code>
   * @return The weatherSpatialInterp.
   */
  ca.wise.project.proto.ScenarioReport.WeatherInterpMethod getWeatherSpatialInterp();

  /**
   * <pre>
   *Is FMC override enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue fmc_override_enabled = 24;</code>
   * @return Whether the fmcOverrideEnabled field is set.
   */
  boolean hasFmcOverrideEnabled();
  /**
   * <pre>
   *Is FMC override enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue fmc_override_enabled = 24;</code>
   * @return The fmcOverrideEnabled.
   */
  com.google.protobuf.BoolValue getFmcOverrideEnabled();
  /**
   * <pre>
   *Is FMC override enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue fmc_override_enabled = 24;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getFmcOverrideEnabledOrBuilder();

  /**
   * <pre>
   *The FMC override, if it is enabled
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue fmc_override = 25;</code>
   * @return Whether the fmcOverride field is set.
   */
  boolean hasFmcOverride();
  /**
   * <pre>
   *The FMC override, if it is enabled
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue fmc_override = 25;</code>
   * @return The fmcOverride.
   */
  com.google.protobuf.DoubleValue getFmcOverride();
  /**
   * <pre>
   *The FMC override, if it is enabled
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue fmc_override = 25;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getFmcOverrideOrBuilder();

  /**
   * <pre>
   *Is the terrain effect enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue terrain_effect = 26;</code>
   * @return Whether the terrainEffect field is set.
   */
  boolean hasTerrainEffect();
  /**
   * <pre>
   *Is the terrain effect enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue terrain_effect = 26;</code>
   * @return The terrainEffect.
   */
  com.google.protobuf.BoolValue getTerrainEffect();
  /**
   * <pre>
   *Is the terrain effect enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue terrain_effect = 26;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getTerrainEffectOrBuilder();

  /**
   * <pre>
   *Greenup on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition greenup = 27;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.SeasonalBurnCondition> 
      getGreenupList();
  /**
   * <pre>
   *Greenup on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition greenup = 27;</code>
   */
  ca.wise.project.proto.ScenarioReport.SeasonalBurnCondition getGreenup(int index);
  /**
   * <pre>
   *Greenup on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition greenup = 27;</code>
   */
  int getGreenupCount();
  /**
   * <pre>
   *Greenup on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition greenup = 27;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.SeasonalBurnConditionOrBuilder> 
      getGreenupOrBuilderList();
  /**
   * <pre>
   *Greenup on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition greenup = 27;</code>
   */
  ca.wise.project.proto.ScenarioReport.SeasonalBurnConditionOrBuilder getGreenupOrBuilder(
      int index);

  /**
   * <pre>
   *Grass Phenology on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_phenology = 28;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.SeasonalBurnCondition> 
      getGrassPhenologyList();
  /**
   * <pre>
   *Grass Phenology on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_phenology = 28;</code>
   */
  ca.wise.project.proto.ScenarioReport.SeasonalBurnCondition getGrassPhenology(int index);
  /**
   * <pre>
   *Grass Phenology on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_phenology = 28;</code>
   */
  int getGrassPhenologyCount();
  /**
   * <pre>
   *Grass Phenology on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_phenology = 28;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.SeasonalBurnConditionOrBuilder> 
      getGrassPhenologyOrBuilderList();
  /**
   * <pre>
   *Grass Phenology on/off dates
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_phenology = 28;</code>
   */
  ca.wise.project.proto.ScenarioReport.SeasonalBurnConditionOrBuilder getGrassPhenologyOrBuilder(
      int index);

  /**
   * <pre>
   *Grass Curing values
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_curing = 29;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.SeasonalBurnCondition> 
      getGrassCuringList();
  /**
   * <pre>
   *Grass Curing values
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_curing = 29;</code>
   */
  ca.wise.project.proto.ScenarioReport.SeasonalBurnCondition getGrassCuring(int index);
  /**
   * <pre>
   *Grass Curing values
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_curing = 29;</code>
   */
  int getGrassCuringCount();
  /**
   * <pre>
   *Grass Curing values
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_curing = 29;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.SeasonalBurnConditionOrBuilder> 
      getGrassCuringOrBuilderList();
  /**
   * <pre>
   *Grass Curing values
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.SeasonalBurnCondition grass_curing = 29;</code>
   */
  ca.wise.project.proto.ScenarioReport.SeasonalBurnConditionOrBuilder getGrassCuringOrBuilder(
      int index);

  /**
   * <pre>
   *Is breaching enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue breaching_enabled = 30;</code>
   * @return Whether the breachingEnabled field is set.
   */
  boolean hasBreachingEnabled();
  /**
   * <pre>
   *Is breaching enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue breaching_enabled = 30;</code>
   * @return The breachingEnabled.
   */
  com.google.protobuf.BoolValue getBreachingEnabled();
  /**
   * <pre>
   *Is breaching enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue breaching_enabled = 30;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getBreachingEnabledOrBuilder();

  /**
   * <pre>
   *Is spotting enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue spotting_enabled = 31;</code>
   * @return Whether the spottingEnabled field is set.
   */
  boolean hasSpottingEnabled();
  /**
   * <pre>
   *Is spotting enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue spotting_enabled = 31;</code>
   * @return The spottingEnabled.
   */
  com.google.protobuf.BoolValue getSpottingEnabled();
  /**
   * <pre>
   *Is spotting enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue spotting_enabled = 31;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getSpottingEnabledOrBuilder();

  /**
   * <pre>
   *Is percentile rate of spread enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue percentile_ros_enabled = 32;</code>
   * @return Whether the percentileRosEnabled field is set.
   */
  boolean hasPercentileRosEnabled();
  /**
   * <pre>
   *Is percentile rate of spread enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue percentile_ros_enabled = 32;</code>
   * @return The percentileRosEnabled.
   */
  com.google.protobuf.BoolValue getPercentileRosEnabled();
  /**
   * <pre>
   *Is percentile rate of spread enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue percentile_ros_enabled = 32;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getPercentileRosEnabledOrBuilder();

  /**
   * <pre>
   *If percentile rate of spread is enabled, use this value
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue percentile_ros = 33;</code>
   * @return Whether the percentileRos field is set.
   */
  boolean hasPercentileRos();
  /**
   * <pre>
   *If percentile rate of spread is enabled, use this value
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue percentile_ros = 33;</code>
   * @return The percentileRos.
   */
  com.google.protobuf.DoubleValue getPercentileRos();
  /**
   * <pre>
   *If percentile rate of spread is enabled, use this value
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue percentile_ros = 33;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getPercentileRosOrBuilder();

  /**
   * <pre>
   *The display interval (ISO8601 duration)
   * </pre>
   *
   * <code>.google.protobuf.StringValue display_interval = 34;</code>
   * @return Whether the displayInterval field is set.
   */
  boolean hasDisplayInterval();
  /**
   * <pre>
   *The display interval (ISO8601 duration)
   * </pre>
   *
   * <code>.google.protobuf.StringValue display_interval = 34;</code>
   * @return The displayInterval.
   */
  com.google.protobuf.StringValue getDisplayInterval();
  /**
   * <pre>
   *The display interval (ISO8601 duration)
   * </pre>
   *
   * <code>.google.protobuf.StringValue display_interval = 34;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDisplayIntervalOrBuilder();

  /**
   * <pre>
   *The timestep during acceleration (ISO8601 duration)
   * </pre>
   *
   * <code>.google.protobuf.StringValue accel_timestep = 35;</code>
   * @return Whether the accelTimestep field is set.
   */
  boolean hasAccelTimestep();
  /**
   * <pre>
   *The timestep during acceleration (ISO8601 duration)
   * </pre>
   *
   * <code>.google.protobuf.StringValue accel_timestep = 35;</code>
   * @return The accelTimestep.
   */
  com.google.protobuf.StringValue getAccelTimestep();
  /**
   * <pre>
   *The timestep during acceleration (ISO8601 duration)
   * </pre>
   *
   * <code>.google.protobuf.StringValue accel_timestep = 35;</code>
   */
  com.google.protobuf.StringValueOrBuilder getAccelTimestepOrBuilder();

  /**
   * <pre>
   *Is dynamic threshold enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue dynamic_threshold = 36;</code>
   * @return Whether the dynamicThreshold field is set.
   */
  boolean hasDynamicThreshold();
  /**
   * <pre>
   *Is dynamic threshold enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue dynamic_threshold = 36;</code>
   * @return The dynamicThreshold.
   */
  com.google.protobuf.BoolValue getDynamicThreshold();
  /**
   * <pre>
   *Is dynamic threshold enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue dynamic_threshold = 36;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getDynamicThresholdOrBuilder();

  /**
   * <pre>
   *The resolution to use for distances
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue distance_resolution = 37;</code>
   * @return Whether the distanceResolution field is set.
   */
  boolean hasDistanceResolution();
  /**
   * <pre>
   *The resolution to use for distances
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue distance_resolution = 37;</code>
   * @return The distanceResolution.
   */
  com.google.protobuf.DoubleValue getDistanceResolution();
  /**
   * <pre>
   *The resolution to use for distances
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue distance_resolution = 37;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDistanceResolutionOrBuilder();

  /**
   * <pre>
   *The resolution to use for perimeters
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue perimeter_resolution = 38;</code>
   * @return Whether the perimeterResolution field is set.
   */
  boolean hasPerimeterResolution();
  /**
   * <pre>
   *The resolution to use for perimeters
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue perimeter_resolution = 38;</code>
   * @return The perimeterResolution.
   */
  com.google.protobuf.DoubleValue getPerimeterResolution();
  /**
   * <pre>
   *The resolution to use for perimeters
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue perimeter_resolution = 38;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getPerimeterResolutionOrBuilder();

  /**
   * <pre>
   *Should the simulation stop if the fire reaches the grid boundary
   * </pre>
   *
   * <code>.google.protobuf.BoolValue stop_at_boundary = 39;</code>
   * @return Whether the stopAtBoundary field is set.
   */
  boolean hasStopAtBoundary();
  /**
   * <pre>
   *Should the simulation stop if the fire reaches the grid boundary
   * </pre>
   *
   * <code>.google.protobuf.BoolValue stop_at_boundary = 39;</code>
   * @return The stopAtBoundary.
   */
  com.google.protobuf.BoolValue getStopAtBoundary();
  /**
   * <pre>
   *Should the simulation stop if the fire reaches the grid boundary
   * </pre>
   *
   * <code>.google.protobuf.BoolValue stop_at_boundary = 39;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getStopAtBoundaryOrBuilder();

  /**
   * <pre>
   *Should non-displayable timesteps be purged
   * </pre>
   *
   * <code>.google.protobuf.BoolValue purge_non_displayable = 40;</code>
   * @return Whether the purgeNonDisplayable field is set.
   */
  boolean hasPurgeNonDisplayable();
  /**
   * <pre>
   *Should non-displayable timesteps be purged
   * </pre>
   *
   * <code>.google.protobuf.BoolValue purge_non_displayable = 40;</code>
   * @return The purgeNonDisplayable.
   */
  com.google.protobuf.BoolValue getPurgeNonDisplayable();
  /**
   * <pre>
   *Should non-displayable timesteps be purged
   * </pre>
   *
   * <code>.google.protobuf.BoolValue purge_non_displayable = 40;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getPurgeNonDisplayableOrBuilder();

  /**
   * <pre>
   *The untis to use for grid cell sizes
   * </pre>
   *
   * <code>.google.protobuf.StringValue grid_units = 41;</code>
   * @return Whether the gridUnits field is set.
   */
  boolean hasGridUnits();
  /**
   * <pre>
   *The untis to use for grid cell sizes
   * </pre>
   *
   * <code>.google.protobuf.StringValue grid_units = 41;</code>
   * @return The gridUnits.
   */
  com.google.protobuf.StringValue getGridUnits();
  /**
   * <pre>
   *The untis to use for grid cell sizes
   * </pre>
   *
   * <code>.google.protobuf.StringValue grid_units = 41;</code>
   */
  com.google.protobuf.StringValueOrBuilder getGridUnitsOrBuilder();

  /**
   * <pre>
   *The grid cell size (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_cell_size = 42;</code>
   * @return Whether the gridCellSize field is set.
   */
  boolean hasGridCellSize();
  /**
   * <pre>
   *The grid cell size (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_cell_size = 42;</code>
   * @return The gridCellSize.
   */
  com.google.protobuf.DoubleValue getGridCellSize();
  /**
   * <pre>
   *The grid cell size (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_cell_size = 42;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridCellSizeOrBuilder();

  /**
   * <pre>
   *The number of columns in the base grid
   * </pre>
   *
   * <code>.google.protobuf.Int32Value grid_columns = 43;</code>
   * @return Whether the gridColumns field is set.
   */
  boolean hasGridColumns();
  /**
   * <pre>
   *The number of columns in the base grid
   * </pre>
   *
   * <code>.google.protobuf.Int32Value grid_columns = 43;</code>
   * @return The gridColumns.
   */
  com.google.protobuf.Int32Value getGridColumns();
  /**
   * <pre>
   *The number of columns in the base grid
   * </pre>
   *
   * <code>.google.protobuf.Int32Value grid_columns = 43;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getGridColumnsOrBuilder();

  /**
   * <pre>
   *The number of rows in the base grid
   * </pre>
   *
   * <code>.google.protobuf.Int32Value grid_rows = 44;</code>
   * @return Whether the gridRows field is set.
   */
  boolean hasGridRows();
  /**
   * <pre>
   *The number of rows in the base grid
   * </pre>
   *
   * <code>.google.protobuf.Int32Value grid_rows = 44;</code>
   * @return The gridRows.
   */
  com.google.protobuf.Int32Value getGridRows();
  /**
   * <pre>
   *The number of rows in the base grid
   * </pre>
   *
   * <code>.google.protobuf.Int32Value grid_rows = 44;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getGridRowsOrBuilder();

  /**
   * <pre>
   *The X location of the lower left corner of the base grid
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_ll_x = 45;</code>
   * @return Whether the gridLlX field is set.
   */
  boolean hasGridLlX();
  /**
   * <pre>
   *The X location of the lower left corner of the base grid
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_ll_x = 45;</code>
   * @return The gridLlX.
   */
  com.google.protobuf.DoubleValue getGridLlX();
  /**
   * <pre>
   *The X location of the lower left corner of the base grid
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_ll_x = 45;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridLlXOrBuilder();

  /**
   * <pre>
   *The Y location of the lower left corner of the base grid
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_ll_y = 46;</code>
   * @return Whether the gridLlY field is set.
   */
  boolean hasGridLlY();
  /**
   * <pre>
   *The Y location of the lower left corner of the base grid
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_ll_y = 46;</code>
   * @return The gridLlY.
   */
  com.google.protobuf.DoubleValue getGridLlY();
  /**
   * <pre>
   *The Y location of the lower left corner of the base grid
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_ll_y = 46;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridLlYOrBuilder();

  /**
   * <pre>
   *The minimum elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_min_elev = 47;</code>
   * @return Whether the gridMinElev field is set.
   */
  boolean hasGridMinElev();
  /**
   * <pre>
   *The minimum elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_min_elev = 47;</code>
   * @return The gridMinElev.
   */
  com.google.protobuf.DoubleValue getGridMinElev();
  /**
   * <pre>
   *The minimum elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_min_elev = 47;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridMinElevOrBuilder();

  /**
   * <pre>
   *The maximum elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_max_elev = 48;</code>
   * @return Whether the gridMaxElev field is set.
   */
  boolean hasGridMaxElev();
  /**
   * <pre>
   *The maximum elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_max_elev = 48;</code>
   * @return The gridMaxElev.
   */
  com.google.protobuf.DoubleValue getGridMaxElev();
  /**
   * <pre>
   *The maximum elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_max_elev = 48;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridMaxElevOrBuilder();

  /**
   * <pre>
   *The mean elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_mean_elev = 49;</code>
   * @return Whether the gridMeanElev field is set.
   */
  boolean hasGridMeanElev();
  /**
   * <pre>
   *The mean elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_mean_elev = 49;</code>
   * @return The gridMeanElev.
   */
  com.google.protobuf.DoubleValue getGridMeanElev();
  /**
   * <pre>
   *The mean elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_mean_elev = 49;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridMeanElevOrBuilder();

  /**
   * <pre>
   *The median elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_median_elev = 50;</code>
   * @return Whether the gridMedianElev field is set.
   */
  boolean hasGridMedianElev();
  /**
   * <pre>
   *The median elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_median_elev = 50;</code>
   * @return The gridMedianElev.
   */
  com.google.protobuf.DoubleValue getGridMedianElev();
  /**
   * <pre>
   *The median elevation (m)
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue grid_median_elev = 50;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getGridMedianElevOrBuilder();

  /**
   * <pre>
   *The timezone used by the project
   * </pre>
   *
   * <code>.google.protobuf.StringValue time_zone = 51;</code>
   * @return Whether the timeZone field is set.
   */
  boolean hasTimeZone();
  /**
   * <pre>
   *The timezone used by the project
   * </pre>
   *
   * <code>.google.protobuf.StringValue time_zone = 51;</code>
   * @return The timeZone.
   */
  com.google.protobuf.StringValue getTimeZone();
  /**
   * <pre>
   *The timezone used by the project
   * </pre>
   *
   * <code>.google.protobuf.StringValue time_zone = 51;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTimeZoneOrBuilder();

  /**
   * <pre>
   *A project for the entire project (if one exists)
   * </pre>
   *
   * <code>.google.protobuf.StringValue project_comment = 52;</code>
   * @return Whether the projectComment field is set.
   */
  boolean hasProjectComment();
  /**
   * <pre>
   *A project for the entire project (if one exists)
   * </pre>
   *
   * <code>.google.protobuf.StringValue project_comment = 52;</code>
   * @return The projectComment.
   */
  com.google.protobuf.StringValue getProjectComment();
  /**
   * <pre>
   *A project for the entire project (if one exists)
   * </pre>
   *
   * <code>.google.protobuf.StringValue project_comment = 52;</code>
   */
  com.google.protobuf.StringValueOrBuilder getProjectCommentOrBuilder();

  /**
   * <pre>
   *The name of the projection file
   * </pre>
   *
   * <code>.google.protobuf.StringValue projection_file = 53;</code>
   * @return Whether the projectionFile field is set.
   */
  boolean hasProjectionFile();
  /**
   * <pre>
   *The name of the projection file
   * </pre>
   *
   * <code>.google.protobuf.StringValue projection_file = 53;</code>
   * @return The projectionFile.
   */
  com.google.protobuf.StringValue getProjectionFile();
  /**
   * <pre>
   *The name of the projection file
   * </pre>
   *
   * <code>.google.protobuf.StringValue projection_file = 53;</code>
   */
  com.google.protobuf.StringValueOrBuilder getProjectionFileOrBuilder();

  /**
   * <pre>
   *The name of the fuel grid file
   * </pre>
   *
   * <code>.google.protobuf.StringValue fuel_grid_file = 54;</code>
   * @return Whether the fuelGridFile field is set.
   */
  boolean hasFuelGridFile();
  /**
   * <pre>
   *The name of the fuel grid file
   * </pre>
   *
   * <code>.google.protobuf.StringValue fuel_grid_file = 54;</code>
   * @return The fuelGridFile.
   */
  com.google.protobuf.StringValue getFuelGridFile();
  /**
   * <pre>
   *The name of the fuel grid file
   * </pre>
   *
   * <code>.google.protobuf.StringValue fuel_grid_file = 54;</code>
   */
  com.google.protobuf.StringValueOrBuilder getFuelGridFileOrBuilder();

  /**
   * <pre>
   *The name of the lookup table file
   * </pre>
   *
   * <code>.google.protobuf.StringValue lookup_table_file = 55;</code>
   * @return Whether the lookupTableFile field is set.
   */
  boolean hasLookupTableFile();
  /**
   * <pre>
   *The name of the lookup table file
   * </pre>
   *
   * <code>.google.protobuf.StringValue lookup_table_file = 55;</code>
   * @return The lookupTableFile.
   */
  com.google.protobuf.StringValue getLookupTableFile();
  /**
   * <pre>
   *The name of the lookup table file
   * </pre>
   *
   * <code>.google.protobuf.StringValue lookup_table_file = 55;</code>
   */
  com.google.protobuf.StringValueOrBuilder getLookupTableFileOrBuilder();

  /**
   * <pre>
   *The name of the elevation grid file
   * </pre>
   *
   * <code>.google.protobuf.StringValue elevation_grid_file = 56;</code>
   * @return Whether the elevationGridFile field is set.
   */
  boolean hasElevationGridFile();
  /**
   * <pre>
   *The name of the elevation grid file
   * </pre>
   *
   * <code>.google.protobuf.StringValue elevation_grid_file = 56;</code>
   * @return The elevationGridFile.
   */
  com.google.protobuf.StringValue getElevationGridFile();
  /**
   * <pre>
   *The name of the elevation grid file
   * </pre>
   *
   * <code>.google.protobuf.StringValue elevation_grid_file = 56;</code>
   */
  com.google.protobuf.StringValueOrBuilder getElevationGridFileOrBuilder();

  /**
   * <pre>
   *A list of attribute filters used by the scenario
   * </pre>
   *
   * <code>repeated string attribute_filters = 57;</code>
   * @return A list containing the attributeFilters.
   */
  java.util.List<java.lang.String>
      getAttributeFiltersList();
  /**
   * <pre>
   *A list of attribute filters used by the scenario
   * </pre>
   *
   * <code>repeated string attribute_filters = 57;</code>
   * @return The count of attributeFilters.
   */
  int getAttributeFiltersCount();
  /**
   * <pre>
   *A list of attribute filters used by the scenario
   * </pre>
   *
   * <code>repeated string attribute_filters = 57;</code>
   * @param index The index of the element to return.
   * @return The attributeFilters at the given index.
   */
  java.lang.String getAttributeFilters(int index);
  /**
   * <pre>
   *A list of attribute filters used by the scenario
   * </pre>
   *
   * <code>repeated string attribute_filters = 57;</code>
   * @param index The index of the value to return.
   * @return The bytes of the attributeFilters at the given index.
   */
  com.google.protobuf.ByteString
      getAttributeFiltersBytes(int index);

  /**
   * <pre>
   *Patches applied to the fuel grid on this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelPatch fuel_patches = 58;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.FuelPatch> 
      getFuelPatchesList();
  /**
   * <pre>
   *Patches applied to the fuel grid on this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelPatch fuel_patches = 58;</code>
   */
  ca.wise.project.proto.ScenarioReport.FuelPatch getFuelPatches(int index);
  /**
   * <pre>
   *Patches applied to the fuel grid on this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelPatch fuel_patches = 58;</code>
   */
  int getFuelPatchesCount();
  /**
   * <pre>
   *Patches applied to the fuel grid on this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelPatch fuel_patches = 58;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.FuelPatchOrBuilder> 
      getFuelPatchesOrBuilderList();
  /**
   * <pre>
   *Patches applied to the fuel grid on this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelPatch fuel_patches = 58;</code>
   */
  ca.wise.project.proto.ScenarioReport.FuelPatchOrBuilder getFuelPatchesOrBuilder(
      int index);

  /**
   * <pre>
   *The list of fuels used in this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelType fuel_types = 59;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.FuelType> 
      getFuelTypesList();
  /**
   * <pre>
   *The list of fuels used in this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelType fuel_types = 59;</code>
   */
  ca.wise.project.proto.ScenarioReport.FuelType getFuelTypes(int index);
  /**
   * <pre>
   *The list of fuels used in this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelType fuel_types = 59;</code>
   */
  int getFuelTypesCount();
  /**
   * <pre>
   *The list of fuels used in this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelType fuel_types = 59;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.FuelTypeOrBuilder> 
      getFuelTypesOrBuilderList();
  /**
   * <pre>
   *The list of fuels used in this scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.FuelType fuel_types = 59;</code>
   */
  ca.wise.project.proto.ScenarioReport.FuelTypeOrBuilder getFuelTypesOrBuilder(
      int index);

  /**
   * <pre>
   *Weather patches and grids used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherPatch weather_patch_grid = 60;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.WeatherPatch> 
      getWeatherPatchGridList();
  /**
   * <pre>
   *Weather patches and grids used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherPatch weather_patch_grid = 60;</code>
   */
  ca.wise.project.proto.ScenarioReport.WeatherPatch getWeatherPatchGrid(int index);
  /**
   * <pre>
   *Weather patches and grids used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherPatch weather_patch_grid = 60;</code>
   */
  int getWeatherPatchGridCount();
  /**
   * <pre>
   *Weather patches and grids used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherPatch weather_patch_grid = 60;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.WeatherPatchOrBuilder> 
      getWeatherPatchGridOrBuilderList();
  /**
   * <pre>
   *Weather patches and grids used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.WeatherPatch weather_patch_grid = 60;</code>
   */
  ca.wise.project.proto.ScenarioReport.WeatherPatchOrBuilder getWeatherPatchGridOrBuilder(
      int index);

  /**
   * <pre>
   *Ignitions used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Ignition ignitions = 61;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.Ignition> 
      getIgnitionsList();
  /**
   * <pre>
   *Ignitions used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Ignition ignitions = 61;</code>
   */
  ca.wise.project.proto.ScenarioReport.Ignition getIgnitions(int index);
  /**
   * <pre>
   *Ignitions used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Ignition ignitions = 61;</code>
   */
  int getIgnitionsCount();
  /**
   * <pre>
   *Ignitions used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Ignition ignitions = 61;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.IgnitionOrBuilder> 
      getIgnitionsOrBuilderList();
  /**
   * <pre>
   *Ignitions used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Ignition ignitions = 61;</code>
   */
  ca.wise.project.proto.ScenarioReport.IgnitionOrBuilder getIgnitionsOrBuilder(
      int index);

  /**
   * <pre>
   *The version of Prometheus that created the report
   * </pre>
   *
   * <code>string prometheus_version = 62;</code>
   * @return The prometheusVersion.
   */
  java.lang.String getPrometheusVersion();
  /**
   * <pre>
   *The version of Prometheus that created the report
   * </pre>
   *
   * <code>string prometheus_version = 62;</code>
   * @return The bytes for prometheusVersion.
   */
  com.google.protobuf.ByteString
      getPrometheusVersionBytes();

  /**
   * <pre>
   *The release date of Prometheus that created the report
   * </pre>
   *
   * <code>string prometheus_date = 63;</code>
   * @return The prometheusDate.
   */
  java.lang.String getPrometheusDate();
  /**
   * <pre>
   *The release date of Prometheus that created the report
   * </pre>
   *
   * <code>string prometheus_date = 63;</code>
   * @return The bytes for prometheusDate.
   */
  com.google.protobuf.ByteString
      getPrometheusDateBytes();

  /**
   * <pre>
   * delta-x
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dx = 64;</code>
   * @return Whether the dx field is set.
   */
  boolean hasDx();
  /**
   * <pre>
   * delta-x
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dx = 64;</code>
   * @return The dx.
   */
  com.google.protobuf.DoubleValue getDx();
  /**
   * <pre>
   * delta-x
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dx = 64;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDxOrBuilder();

  /**
   * <pre>
   * delta-y
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dy = 65;</code>
   * @return Whether the dy field is set.
   */
  boolean hasDy();
  /**
   * <pre>
   * delta-y
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dy = 65;</code>
   * @return The dy.
   */
  com.google.protobuf.DoubleValue getDy();
  /**
   * <pre>
   * delta-y
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dy = 65;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDyOrBuilder();

  /**
   * <pre>
   * delta-time
   * </pre>
   *
   * <code>.google.protobuf.StringValue dt = 66;</code>
   * @return Whether the dt field is set.
   */
  boolean hasDt();
  /**
   * <pre>
   * delta-time
   * </pre>
   *
   * <code>.google.protobuf.StringValue dt = 66;</code>
   * @return The dt.
   */
  com.google.protobuf.StringValue getDt();
  /**
   * <pre>
   * delta-time
   * </pre>
   *
   * <code>.google.protobuf.StringValue dt = 66;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDtOrBuilder();

  /**
   * <pre>
   * delta-winddirection
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dwd = 67;</code>
   * @return Whether the dwd field is set.
   */
  boolean hasDwd();
  /**
   * <pre>
   * delta-winddirection
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dwd = 67;</code>
   * @return The dwd.
   */
  com.google.protobuf.DoubleValue getDwd();
  /**
   * <pre>
   * delta-winddirection
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue dwd = 67;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDwdOrBuilder();

  /**
   * <pre>
   * override-winddirection
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue owd = 68;</code>
   * @return Whether the owd field is set.
   */
  boolean hasOwd();
  /**
   * <pre>
   * override-winddirection
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue owd = 68;</code>
   * @return The owd.
   */
  com.google.protobuf.DoubleValue getOwd();
  /**
   * <pre>
   * override-winddirection
   * </pre>
   *
   * <code>.google.protobuf.DoubleValue owd = 68;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getOwdOrBuilder();

  /**
   * <pre>
   *A list of assets used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Asset assets = 69;</code>
   */
  java.util.List<ca.wise.project.proto.ScenarioReport.Asset> 
      getAssetsList();
  /**
   * <pre>
   *A list of assets used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Asset assets = 69;</code>
   */
  ca.wise.project.proto.ScenarioReport.Asset getAssets(int index);
  /**
   * <pre>
   *A list of assets used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Asset assets = 69;</code>
   */
  int getAssetsCount();
  /**
   * <pre>
   *A list of assets used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Asset assets = 69;</code>
   */
  java.util.List<? extends ca.wise.project.proto.ScenarioReport.AssetOrBuilder> 
      getAssetsOrBuilderList();
  /**
   * <pre>
   *A list of assets used by the scenario
   * </pre>
   *
   * <code>repeated .WISE.ProjectProto.ScenarioReport.Asset assets = 69;</code>
   */
  ca.wise.project.proto.ScenarioReport.AssetOrBuilder getAssetsOrBuilder(
      int index);

  /**
   * <pre>
   *Is a false origin used for internally storing grid data
   * </pre>
   *
   * <code>.google.protobuf.BoolValue use_false_origin = 70;</code>
   * @return Whether the useFalseOrigin field is set.
   */
  boolean hasUseFalseOrigin();
  /**
   * <pre>
   *Is a false origin used for internally storing grid data
   * </pre>
   *
   * <code>.google.protobuf.BoolValue use_false_origin = 70;</code>
   * @return The useFalseOrigin.
   */
  com.google.protobuf.BoolValue getUseFalseOrigin();
  /**
   * <pre>
   *Is a false origin used for internally storing grid data
   * </pre>
   *
   * <code>.google.protobuf.BoolValue use_false_origin = 70;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getUseFalseOriginOrBuilder();

  /**
   * <pre>
   *Is a false scale used for internally storing grid data
   * </pre>
   *
   * <code>.google.protobuf.BoolValue use_false_scaling = 71;</code>
   * @return Whether the useFalseScaling field is set.
   */
  boolean hasUseFalseScaling();
  /**
   * <pre>
   *Is a false scale used for internally storing grid data
   * </pre>
   *
   * <code>.google.protobuf.BoolValue use_false_scaling = 71;</code>
   * @return The useFalseScaling.
   */
  com.google.protobuf.BoolValue getUseFalseScaling();
  /**
   * <pre>
   *Is a false scale used for internally storing grid data
   * </pre>
   *
   * <code>.google.protobuf.BoolValue use_false_scaling = 71;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getUseFalseScalingOrBuilder();

  public ca.wise.project.proto.ScenarioReport.InterpCase getInterpCase();
}
