// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vectorCollection.proto

package ca.wise.project.proto;

public final class VectorCollectionOuterClass {
  private VectorCollectionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_ProjectProto_VectorCollection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_ProjectProto_VectorCollection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_ProjectProto_VectorCollection_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_ProjectProto_VectorCollection_Vector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026vectorCollection.proto\022\021WISE.ProjectPr" +
      "oto\032\021cwfgmFilter.proto\032\027projectGridFilte" +
      "r.proto\032\022staticPoints.proto\"\242\002\n\020VectorCo" +
      "llection\022\017\n\007version\030\001 \001(\005\022?\n\007vectors\030\002 \003" +
      "(\0132*.WISE.ProjectProto.VectorCollection." +
      "VectorB\002\030\001\0225\n\nvectorData\030\003 \003(\0132!.WISE.Gr" +
      "idProto.CwfgmVectorFilter\032\204\001\n\006Vector\0228\n\006" +
      "filter\030\001 \001(\0132&.WISE.ProjectProto.Project" +
      "VectorFilterH\000\0224\n\006points\030\002 \001(\0132\036.WISE.Pr" +
      "ojectProto.StaticPointB\002\030\001H\000:\002\030\001B\006\n\004data" +
      "B-\n\025ca.wise.project.protoP\001\252\002\021WISE.Proje" +
      "ctProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.wise.grid.proto.CwfgmFilter.getDescriptor(),
          ca.wise.project.proto.ProjectGridFilter.getDescriptor(),
          ca.wise.project.proto.StaticPoints.getDescriptor(),
        });
    internal_static_WISE_ProjectProto_VectorCollection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_ProjectProto_VectorCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_ProjectProto_VectorCollection_descriptor,
        new java.lang.String[] { "Version", "Vectors", "VectorData", });
    internal_static_WISE_ProjectProto_VectorCollection_Vector_descriptor =
      internal_static_WISE_ProjectProto_VectorCollection_descriptor.getNestedTypes().get(0);
    internal_static_WISE_ProjectProto_VectorCollection_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_ProjectProto_VectorCollection_Vector_descriptor,
        new java.lang.String[] { "Filter", "Points", "Data", });
    ca.wise.grid.proto.CwfgmFilter.getDescriptor();
    ca.wise.project.proto.ProjectGridFilter.getDescriptor();
    ca.wise.project.proto.StaticPoints.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
