// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: projectGridFilter.proto

package ca.wise.project.proto;

@java.lang.Deprecated public interface ProjectVectorFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.ProjectVectorFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string comments = 3;</code>
   * @return The comments.
   */
  java.lang.String getComments();
  /**
   * <code>string comments = 3;</code>
   * @return The bytes for comments.
   */
  com.google.protobuf.ByteString
      getCommentsBytes();

  /**
   * <code>uint32 color = 4;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <code>uint32 fillColor = 5;</code>
   * @return The fillColor.
   */
  int getFillColor();

  /**
   * <code>uint32 symbol = 6;</code>
   * @return The symbol.
   */
  int getSymbol();

  /**
   * <code>sint32 width = 7;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>bool imported = 8;</code>
   * @return The imported.
   */
  boolean getImported();

  /**
   * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
   * @return The filter.
   */
  ca.wise.grid.proto.CwfgmVectorFilter getFilter();
  /**
   * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
   */
  ca.wise.grid.proto.CwfgmVectorFilterOrBuilder getFilterOrBuilder();

  /**
   * <code>string filename = 10 [deprecated = true];</code>
   * @return The filename.
   */
  @java.lang.Deprecated java.lang.String getFilename();
  /**
   * <code>string filename = 10 [deprecated = true];</code>
   * @return The bytes for filename.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>.WISE.ProjectProto.ProjectVectorFilter.VectorFile file = 11;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.WISE.ProjectProto.ProjectVectorFilter.VectorFile file = 11;</code>
   * @return The file.
   */
  ca.wise.project.proto.ProjectVectorFilter.VectorFile getFile();
  /**
   * <code>.WISE.ProjectProto.ProjectVectorFilter.VectorFile file = 11;</code>
   */
  ca.wise.project.proto.ProjectVectorFilter.VectorFileOrBuilder getFileOrBuilder();

  public ca.wise.project.proto.ProjectVectorFilter.DataCase getDataCase();
}
