// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staticPoints.proto

package ca.wise.project.proto;

/**
 * Protobuf type {@code WISE.ProjectProto.StaticPoint}
 */
@java.lang.Deprecated public final class StaticPoint extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.ProjectProto.StaticPoint)
    StaticPointOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StaticPoint.newBuilder() to construct.
  private StaticPoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StaticPoint() {
    name_ = "";
    comments_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StaticPoint();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StaticPoint(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            comments_ = s;
            break;
          }
          case 32: {

            color_ = input.readUInt32();
            break;
          }
          case 42: {
            ca.hss.math.proto.GeoPoly.Builder subBuilder = null;
            if (points_ != null) {
              subBuilder = points_.toBuilder();
            }
            points_ = input.readMessage(ca.hss.math.proto.GeoPoly.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(points_);
              points_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            valid_ = input.readBool();
            break;
          }
          case 56: {

            size_ = input.readUInt32();
            break;
          }
          case 64: {

            imported_ = input.readBool();
            break;
          }
          case 74: {
            ca.wise.grid.proto.CwfgmVectorFilter.Builder subBuilder = null;
            if (filter_ != null) {
              subBuilder = filter_.toBuilder();
            }
            filter_ = input.readMessage(ca.wise.grid.proto.CwfgmVectorFilter.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filter_);
              filter_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.project.proto.StaticPoints.internal_static_WISE_ProjectProto_StaticPoint_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.project.proto.StaticPoints.internal_static_WISE_ProjectProto_StaticPoint_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.project.proto.StaticPoint.class, ca.wise.project.proto.StaticPoint.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMENTS_FIELD_NUMBER = 3;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 3;</code>
   * @return The comments.
   */
  @java.lang.Override
  public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 3;</code>
   * @return The bytes for comments.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private int color_;
  /**
   * <code>uint32 color = 4;</code>
   * @return The color.
   */
  @java.lang.Override
  public int getColor() {
    return color_;
  }

  public static final int POINTS_FIELD_NUMBER = 5;
  private ca.hss.math.proto.GeoPoly points_;
  /**
   * <code>.Geography.GeoPoly points = 5;</code>
   * @return Whether the points field is set.
   */
  @java.lang.Override
  public boolean hasPoints() {
    return points_ != null;
  }
  /**
   * <code>.Geography.GeoPoly points = 5;</code>
   * @return The points.
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPoly getPoints() {
    return points_ == null ? ca.hss.math.proto.GeoPoly.getDefaultInstance() : points_;
  }
  /**
   * <code>.Geography.GeoPoly points = 5;</code>
   */
  @java.lang.Override
  public ca.hss.math.proto.GeoPolyOrBuilder getPointsOrBuilder() {
    return getPoints();
  }

  public static final int VALID_FIELD_NUMBER = 6;
  private boolean valid_;
  /**
   * <code>bool valid = 6;</code>
   * @return The valid.
   */
  @java.lang.Override
  public boolean getValid() {
    return valid_;
  }

  public static final int SIZE_FIELD_NUMBER = 7;
  private int size_;
  /**
   * <code>uint32 size = 7;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int IMPORTED_FIELD_NUMBER = 8;
  private boolean imported_;
  /**
   * <code>bool imported = 8;</code>
   * @return The imported.
   */
  @java.lang.Override
  public boolean getImported() {
    return imported_;
  }

  public static final int FILTER_FIELD_NUMBER = 9;
  private ca.wise.grid.proto.CwfgmVectorFilter filter_;
  /**
   * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return filter_ != null;
  }
  /**
   * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
   * @return The filter.
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmVectorFilter getFilter() {
    return filter_ == null ? ca.wise.grid.proto.CwfgmVectorFilter.getDefaultInstance() : filter_;
  }
  /**
   * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmVectorFilterOrBuilder getFilterOrBuilder() {
    return getFilter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getCommentsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, comments_);
    }
    if (color_ != 0) {
      output.writeUInt32(4, color_);
    }
    if (points_ != null) {
      output.writeMessage(5, getPoints());
    }
    if (valid_ != false) {
      output.writeBool(6, valid_);
    }
    if (size_ != 0) {
      output.writeUInt32(7, size_);
    }
    if (imported_ != false) {
      output.writeBool(8, imported_);
    }
    if (filter_ != null) {
      output.writeMessage(9, getFilter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getCommentsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, comments_);
    }
    if (color_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, color_);
    }
    if (points_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPoints());
    }
    if (valid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, valid_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, size_);
    }
    if (imported_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, imported_);
    }
    if (filter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getFilter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.project.proto.StaticPoint)) {
      return super.equals(obj);
    }
    ca.wise.project.proto.StaticPoint other = (ca.wise.project.proto.StaticPoint) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getComments()
        .equals(other.getComments())) return false;
    if (getColor()
        != other.getColor()) return false;
    if (hasPoints() != other.hasPoints()) return false;
    if (hasPoints()) {
      if (!getPoints()
          .equals(other.getPoints())) return false;
    }
    if (getValid()
        != other.getValid()) return false;
    if (getSize()
        != other.getSize()) return false;
    if (getImported()
        != other.getImported()) return false;
    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getComments().hashCode();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor();
    if (hasPoints()) {
      hash = (37 * hash) + POINTS_FIELD_NUMBER;
      hash = (53 * hash) + getPoints().hashCode();
    }
    hash = (37 * hash) + VALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getValid());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + IMPORTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImported());
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.project.proto.StaticPoint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.StaticPoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.StaticPoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.StaticPoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.project.proto.StaticPoint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.StaticPoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.StaticPoint)
      ca.wise.project.proto.StaticPointOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.StaticPoints.internal_static_WISE_ProjectProto_StaticPoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.StaticPoints.internal_static_WISE_ProjectProto_StaticPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.StaticPoint.class, ca.wise.project.proto.StaticPoint.Builder.class);
    }

    // Construct using ca.wise.project.proto.StaticPoint.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      name_ = "";

      comments_ = "";

      color_ = 0;

      if (pointsBuilder_ == null) {
        points_ = null;
      } else {
        points_ = null;
        pointsBuilder_ = null;
      }
      valid_ = false;

      size_ = 0;

      imported_ = false;

      if (filterBuilder_ == null) {
        filter_ = null;
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.project.proto.StaticPoints.internal_static_WISE_ProjectProto_StaticPoint_descriptor;
    }

    @java.lang.Override
    public ca.wise.project.proto.StaticPoint getDefaultInstanceForType() {
      return ca.wise.project.proto.StaticPoint.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.project.proto.StaticPoint build() {
      ca.wise.project.proto.StaticPoint result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.project.proto.StaticPoint buildPartial() {
      ca.wise.project.proto.StaticPoint result = new ca.wise.project.proto.StaticPoint(this);
      result.version_ = version_;
      result.name_ = name_;
      result.comments_ = comments_;
      result.color_ = color_;
      if (pointsBuilder_ == null) {
        result.points_ = points_;
      } else {
        result.points_ = pointsBuilder_.build();
      }
      result.valid_ = valid_;
      result.size_ = size_;
      result.imported_ = imported_;
      if (filterBuilder_ == null) {
        result.filter_ = filter_;
      } else {
        result.filter_ = filterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.project.proto.StaticPoint) {
        return mergeFrom((ca.wise.project.proto.StaticPoint)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.project.proto.StaticPoint other) {
      if (other == ca.wise.project.proto.StaticPoint.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getComments().isEmpty()) {
        comments_ = other.comments_;
        onChanged();
      }
      if (other.getColor() != 0) {
        setColor(other.getColor());
      }
      if (other.hasPoints()) {
        mergePoints(other.getPoints());
      }
      if (other.getValid() != false) {
        setValid(other.getValid());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (other.getImported() != false) {
        setImported(other.getImported());
      }
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.project.proto.StaticPoint parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.project.proto.StaticPoint) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 3;</code>
     * @return The comments.
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 3;</code>
     * @return The bytes for comments.
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 3;</code>
     * @param value The comments to set.
     * @return This builder for chaining.
     */
    public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearComments() {
      
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 3;</code>
     * @param value The bytes for comments to set.
     * @return This builder for chaining.
     */
    public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comments_ = value;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <code>uint32 color = 4;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }
    /**
     * <code>uint32 color = 4;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {
      
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 color = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      
      color_ = 0;
      onChanged();
      return this;
    }

    private ca.hss.math.proto.GeoPoly points_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder> pointsBuilder_;
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     * @return Whether the points field is set.
     */
    public boolean hasPoints() {
      return pointsBuilder_ != null || points_ != null;
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     * @return The points.
     */
    public ca.hss.math.proto.GeoPoly getPoints() {
      if (pointsBuilder_ == null) {
        return points_ == null ? ca.hss.math.proto.GeoPoly.getDefaultInstance() : points_;
      } else {
        return pointsBuilder_.getMessage();
      }
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    public Builder setPoints(ca.hss.math.proto.GeoPoly value) {
      if (pointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        points_ = value;
        onChanged();
      } else {
        pointsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    public Builder setPoints(
        ca.hss.math.proto.GeoPoly.Builder builderForValue) {
      if (pointsBuilder_ == null) {
        points_ = builderForValue.build();
        onChanged();
      } else {
        pointsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    public Builder mergePoints(ca.hss.math.proto.GeoPoly value) {
      if (pointsBuilder_ == null) {
        if (points_ != null) {
          points_ =
            ca.hss.math.proto.GeoPoly.newBuilder(points_).mergeFrom(value).buildPartial();
        } else {
          points_ = value;
        }
        onChanged();
      } else {
        pointsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    public Builder clearPoints() {
      if (pointsBuilder_ == null) {
        points_ = null;
        onChanged();
      } else {
        points_ = null;
        pointsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    public ca.hss.math.proto.GeoPoly.Builder getPointsBuilder() {
      
      onChanged();
      return getPointsFieldBuilder().getBuilder();
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    public ca.hss.math.proto.GeoPolyOrBuilder getPointsOrBuilder() {
      if (pointsBuilder_ != null) {
        return pointsBuilder_.getMessageOrBuilder();
      } else {
        return points_ == null ?
            ca.hss.math.proto.GeoPoly.getDefaultInstance() : points_;
      }
    }
    /**
     * <code>.Geography.GeoPoly points = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder> 
        getPointsFieldBuilder() {
      if (pointsBuilder_ == null) {
        pointsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.hss.math.proto.GeoPoly, ca.hss.math.proto.GeoPoly.Builder, ca.hss.math.proto.GeoPolyOrBuilder>(
                getPoints(),
                getParentForChildren(),
                isClean());
        points_ = null;
      }
      return pointsBuilder_;
    }

    private boolean valid_ ;
    /**
     * <code>bool valid = 6;</code>
     * @return The valid.
     */
    @java.lang.Override
    public boolean getValid() {
      return valid_;
    }
    /**
     * <code>bool valid = 6;</code>
     * @param value The valid to set.
     * @return This builder for chaining.
     */
    public Builder setValid(boolean value) {
      
      valid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool valid = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearValid() {
      
      valid_ = false;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>uint32 size = 7;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>uint32 size = 7;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0;
      onChanged();
      return this;
    }

    private boolean imported_ ;
    /**
     * <code>bool imported = 8;</code>
     * @return The imported.
     */
    @java.lang.Override
    public boolean getImported() {
      return imported_;
    }
    /**
     * <code>bool imported = 8;</code>
     * @param value The imported to set.
     * @return This builder for chaining.
     */
    public Builder setImported(boolean value) {
      
      imported_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool imported = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearImported() {
      
      imported_ = false;
      onChanged();
      return this;
    }

    private ca.wise.grid.proto.CwfgmVectorFilter filter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmVectorFilter, ca.wise.grid.proto.CwfgmVectorFilter.Builder, ca.wise.grid.proto.CwfgmVectorFilterOrBuilder> filterBuilder_;
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return filterBuilder_ != null || filter_ != null;
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     * @return The filter.
     */
    public ca.wise.grid.proto.CwfgmVectorFilter getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? ca.wise.grid.proto.CwfgmVectorFilter.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    public Builder setFilter(ca.wise.grid.proto.CwfgmVectorFilter value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
        onChanged();
      } else {
        filterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    public Builder setFilter(
        ca.wise.grid.proto.CwfgmVectorFilter.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
        onChanged();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    public Builder mergeFilter(ca.wise.grid.proto.CwfgmVectorFilter value) {
      if (filterBuilder_ == null) {
        if (filter_ != null) {
          filter_ =
            ca.wise.grid.proto.CwfgmVectorFilter.newBuilder(filter_).mergeFrom(value).buildPartial();
        } else {
          filter_ = value;
        }
        onChanged();
      } else {
        filterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    public Builder clearFilter() {
      if (filterBuilder_ == null) {
        filter_ = null;
        onChanged();
      } else {
        filter_ = null;
        filterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilter.Builder getFilterBuilder() {
      
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilterOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            ca.wise.grid.proto.CwfgmVectorFilter.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>.WISE.GridProto.CwfgmVectorFilter filter = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ca.wise.grid.proto.CwfgmVectorFilter, ca.wise.grid.proto.CwfgmVectorFilter.Builder, ca.wise.grid.proto.CwfgmVectorFilterOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ca.wise.grid.proto.CwfgmVectorFilter, ca.wise.grid.proto.CwfgmVectorFilter.Builder, ca.wise.grid.proto.CwfgmVectorFilterOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.StaticPoint)
  }

  // @@protoc_insertion_point(class_scope:WISE.ProjectProto.StaticPoint)
  private static final ca.wise.project.proto.StaticPoint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.project.proto.StaticPoint();
  }

  public static ca.wise.project.proto.StaticPoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StaticPoint>
      PARSER = new com.google.protobuf.AbstractParser<StaticPoint>() {
    @java.lang.Override
    public StaticPoint parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StaticPoint(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StaticPoint> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StaticPoint> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.project.proto.StaticPoint getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

