// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vectorCollection.proto

package ca.wise.project.proto;

/**
 * Protobuf type {@code WISE.ProjectProto.VectorCollection}
 */
public final class VectorCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.ProjectProto.VectorCollection)
    VectorCollectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VectorCollection.newBuilder() to construct.
  private VectorCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VectorCollection() {
    vectors_ = java.util.Collections.emptyList();
    vectorData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VectorCollection();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VectorCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              vectors_ = new java.util.ArrayList<ca.wise.project.proto.VectorCollection.Vector>();
              mutable_bitField0_ |= 0x00000001;
            }
            vectors_.add(
                input.readMessage(ca.wise.project.proto.VectorCollection.Vector.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              vectorData_ = new java.util.ArrayList<ca.wise.grid.proto.CwfgmVectorFilter>();
              mutable_bitField0_ |= 0x00000002;
            }
            vectorData_.add(
                input.readMessage(ca.wise.grid.proto.CwfgmVectorFilter.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        vectors_ = java.util.Collections.unmodifiableList(vectors_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        vectorData_ = java.util.Collections.unmodifiableList(vectorData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.project.proto.VectorCollection.class, ca.wise.project.proto.VectorCollection.Builder.class);
  }

  @java.lang.Deprecated public interface VectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.ProjectProto.VectorCollection.Vector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
     * @return Whether the filter field is set.
     */
    boolean hasFilter();
    /**
     * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
     * @return The filter.
     */
    ca.wise.project.proto.ProjectVectorFilter getFilter();
    /**
     * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
     */
    ca.wise.project.proto.ProjectVectorFilterOrBuilder getFilterOrBuilder();

    /**
     * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
     * @return Whether the points field is set.
     */
    @java.lang.Deprecated boolean hasPoints();
    /**
     * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
     * @return The points.
     */
    @java.lang.Deprecated ca.wise.project.proto.StaticPoint getPoints();
    /**
     * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated ca.wise.project.proto.StaticPointOrBuilder getPointsOrBuilder();

    public ca.wise.project.proto.VectorCollection.Vector.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.VectorCollection.Vector}
   */
  @java.lang.Deprecated public static final class Vector extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.ProjectProto.VectorCollection.Vector)
      VectorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vector.newBuilder() to construct.
    private Vector(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vector() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vector();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ca.wise.project.proto.ProjectVectorFilter.Builder subBuilder = null;
              if (dataCase_ == 1) {
                subBuilder = ((ca.wise.project.proto.ProjectVectorFilter) data_).toBuilder();
              }
              data_ =
                  input.readMessage(ca.wise.project.proto.ProjectVectorFilter.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ca.wise.project.proto.ProjectVectorFilter) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 1;
              break;
            }
            case 18: {
              ca.wise.project.proto.StaticPoint.Builder subBuilder = null;
              if (dataCase_ == 2) {
                subBuilder = ((ca.wise.project.proto.StaticPoint) data_).toBuilder();
              }
              data_ =
                  input.readMessage(ca.wise.project.proto.StaticPoint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ca.wise.project.proto.StaticPoint) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_Vector_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_Vector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.VectorCollection.Vector.class, ca.wise.project.proto.VectorCollection.Vector.Builder.class);
    }

    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      FILTER(1),
      @java.lang.Deprecated POINTS(2),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1: return FILTER;
          case 2: return POINTS;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int FILTER_FIELD_NUMBER = 1;
    /**
     * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
     * @return Whether the filter field is set.
     */
    @java.lang.Override
    public boolean hasFilter() {
      return dataCase_ == 1;
    }
    /**
     * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
     * @return The filter.
     */
    @java.lang.Override
    public ca.wise.project.proto.ProjectVectorFilter getFilter() {
      if (dataCase_ == 1) {
         return (ca.wise.project.proto.ProjectVectorFilter) data_;
      }
      return ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance();
    }
    /**
     * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
     */
    @java.lang.Override
    public ca.wise.project.proto.ProjectVectorFilterOrBuilder getFilterOrBuilder() {
      if (dataCase_ == 1) {
         return (ca.wise.project.proto.ProjectVectorFilter) data_;
      }
      return ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance();
    }

    public static final int POINTS_FIELD_NUMBER = 2;
    /**
     * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
     * @return Whether the points field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated public boolean hasPoints() {
      return dataCase_ == 2;
    }
    /**
     * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
     * @return The points.
     */
    @java.lang.Override
    @java.lang.Deprecated public ca.wise.project.proto.StaticPoint getPoints() {
      if (dataCase_ == 2) {
         return (ca.wise.project.proto.StaticPoint) data_;
      }
      return ca.wise.project.proto.StaticPoint.getDefaultInstance();
    }
    /**
     * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public ca.wise.project.proto.StaticPointOrBuilder getPointsOrBuilder() {
      if (dataCase_ == 2) {
         return (ca.wise.project.proto.StaticPoint) data_;
      }
      return ca.wise.project.proto.StaticPoint.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeMessage(1, (ca.wise.project.proto.ProjectVectorFilter) data_);
      }
      if (dataCase_ == 2) {
        output.writeMessage(2, (ca.wise.project.proto.StaticPoint) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ca.wise.project.proto.ProjectVectorFilter) data_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ca.wise.project.proto.StaticPoint) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.project.proto.VectorCollection.Vector)) {
        return super.equals(obj);
      }
      ca.wise.project.proto.VectorCollection.Vector other = (ca.wise.project.proto.VectorCollection.Vector) obj;

      if (!getDataCase().equals(other.getDataCase())) return false;
      switch (dataCase_) {
        case 1:
          if (!getFilter()
              .equals(other.getFilter())) return false;
          break;
        case 2:
          if (!getPoints()
              .equals(other.getPoints())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + FILTER_FIELD_NUMBER;
          hash = (53 * hash) + getFilter().hashCode();
          break;
        case 2:
          hash = (37 * hash) + POINTS_FIELD_NUMBER;
          hash = (53 * hash) + getPoints().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.project.proto.VectorCollection.Vector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.project.proto.VectorCollection.Vector prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WISE.ProjectProto.VectorCollection.Vector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.VectorCollection.Vector)
        ca.wise.project.proto.VectorCollection.VectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_Vector_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_Vector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.project.proto.VectorCollection.Vector.class, ca.wise.project.proto.VectorCollection.Vector.Builder.class);
      }

      // Construct using ca.wise.project.proto.VectorCollection.Vector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_Vector_descriptor;
      }

      @java.lang.Override
      public ca.wise.project.proto.VectorCollection.Vector getDefaultInstanceForType() {
        return ca.wise.project.proto.VectorCollection.Vector.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.project.proto.VectorCollection.Vector build() {
        ca.wise.project.proto.VectorCollection.Vector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.project.proto.VectorCollection.Vector buildPartial() {
        ca.wise.project.proto.VectorCollection.Vector result = new ca.wise.project.proto.VectorCollection.Vector(this);
        if (dataCase_ == 1) {
          if (filterBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = filterBuilder_.build();
          }
        }
        if (dataCase_ == 2) {
          if (pointsBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = pointsBuilder_.build();
          }
        }
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.project.proto.VectorCollection.Vector) {
          return mergeFrom((ca.wise.project.proto.VectorCollection.Vector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.project.proto.VectorCollection.Vector other) {
        if (other == ca.wise.project.proto.VectorCollection.Vector.getDefaultInstance()) return this;
        switch (other.getDataCase()) {
          case FILTER: {
            mergeFilter(other.getFilter());
            break;
          }
          case POINTS: {
            mergePoints(other.getPoints());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.project.proto.VectorCollection.Vector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.project.proto.VectorCollection.Vector) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.project.proto.ProjectVectorFilter, ca.wise.project.proto.ProjectVectorFilter.Builder, ca.wise.project.proto.ProjectVectorFilterOrBuilder> filterBuilder_;
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       * @return Whether the filter field is set.
       */
      @java.lang.Override
      public boolean hasFilter() {
        return dataCase_ == 1;
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       * @return The filter.
       */
      @java.lang.Override
      public ca.wise.project.proto.ProjectVectorFilter getFilter() {
        if (filterBuilder_ == null) {
          if (dataCase_ == 1) {
            return (ca.wise.project.proto.ProjectVectorFilter) data_;
          }
          return ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance();
        } else {
          if (dataCase_ == 1) {
            return filterBuilder_.getMessage();
          }
          return ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      public Builder setFilter(ca.wise.project.proto.ProjectVectorFilter value) {
        if (filterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          filterBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      public Builder setFilter(
          ca.wise.project.proto.ProjectVectorFilter.Builder builderForValue) {
        if (filterBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          filterBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      public Builder mergeFilter(ca.wise.project.proto.ProjectVectorFilter value) {
        if (filterBuilder_ == null) {
          if (dataCase_ == 1 &&
              data_ != ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance()) {
            data_ = ca.wise.project.proto.ProjectVectorFilter.newBuilder((ca.wise.project.proto.ProjectVectorFilter) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 1) {
            filterBuilder_.mergeFrom(value);
          }
          filterBuilder_.setMessage(value);
        }
        dataCase_ = 1;
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      public Builder clearFilter() {
        if (filterBuilder_ == null) {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 1) {
            dataCase_ = 0;
            data_ = null;
          }
          filterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      public ca.wise.project.proto.ProjectVectorFilter.Builder getFilterBuilder() {
        return getFilterFieldBuilder().getBuilder();
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      @java.lang.Override
      public ca.wise.project.proto.ProjectVectorFilterOrBuilder getFilterOrBuilder() {
        if ((dataCase_ == 1) && (filterBuilder_ != null)) {
          return filterBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 1) {
            return (ca.wise.project.proto.ProjectVectorFilter) data_;
          }
          return ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.ProjectProto.ProjectVectorFilter filter = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.project.proto.ProjectVectorFilter, ca.wise.project.proto.ProjectVectorFilter.Builder, ca.wise.project.proto.ProjectVectorFilterOrBuilder> 
          getFilterFieldBuilder() {
        if (filterBuilder_ == null) {
          if (!(dataCase_ == 1)) {
            data_ = ca.wise.project.proto.ProjectVectorFilter.getDefaultInstance();
          }
          filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.wise.project.proto.ProjectVectorFilter, ca.wise.project.proto.ProjectVectorFilter.Builder, ca.wise.project.proto.ProjectVectorFilterOrBuilder>(
                  (ca.wise.project.proto.ProjectVectorFilter) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 1;
        onChanged();;
        return filterBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.project.proto.StaticPoint, ca.wise.project.proto.StaticPoint.Builder, ca.wise.project.proto.StaticPointOrBuilder> pointsBuilder_;
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       * @return Whether the points field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated public boolean hasPoints() {
        return dataCase_ == 2;
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       * @return The points.
       */
      @java.lang.Override
      @java.lang.Deprecated public ca.wise.project.proto.StaticPoint getPoints() {
        if (pointsBuilder_ == null) {
          if (dataCase_ == 2) {
            return (ca.wise.project.proto.StaticPoint) data_;
          }
          return ca.wise.project.proto.StaticPoint.getDefaultInstance();
        } else {
          if (dataCase_ == 2) {
            return pointsBuilder_.getMessage();
          }
          return ca.wise.project.proto.StaticPoint.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setPoints(ca.wise.project.proto.StaticPoint value) {
        if (pointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          pointsBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setPoints(
          ca.wise.project.proto.StaticPoint.Builder builderForValue) {
        if (pointsBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          pointsBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder mergePoints(ca.wise.project.proto.StaticPoint value) {
        if (pointsBuilder_ == null) {
          if (dataCase_ == 2 &&
              data_ != ca.wise.project.proto.StaticPoint.getDefaultInstance()) {
            data_ = ca.wise.project.proto.StaticPoint.newBuilder((ca.wise.project.proto.StaticPoint) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 2) {
            pointsBuilder_.mergeFrom(value);
          }
          pointsBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearPoints() {
        if (pointsBuilder_ == null) {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
          }
          pointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      @java.lang.Deprecated public ca.wise.project.proto.StaticPoint.Builder getPointsBuilder() {
        return getPointsFieldBuilder().getBuilder();
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      @java.lang.Override
      @java.lang.Deprecated public ca.wise.project.proto.StaticPointOrBuilder getPointsOrBuilder() {
        if ((dataCase_ == 2) && (pointsBuilder_ != null)) {
          return pointsBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 2) {
            return (ca.wise.project.proto.StaticPoint) data_;
          }
          return ca.wise.project.proto.StaticPoint.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.ProjectProto.StaticPoint points = 2 [deprecated = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.project.proto.StaticPoint, ca.wise.project.proto.StaticPoint.Builder, ca.wise.project.proto.StaticPointOrBuilder> 
          getPointsFieldBuilder() {
        if (pointsBuilder_ == null) {
          if (!(dataCase_ == 2)) {
            data_ = ca.wise.project.proto.StaticPoint.getDefaultInstance();
          }
          pointsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.wise.project.proto.StaticPoint, ca.wise.project.proto.StaticPoint.Builder, ca.wise.project.proto.StaticPointOrBuilder>(
                  (ca.wise.project.proto.StaticPoint) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 2;
        onChanged();;
        return pointsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.VectorCollection.Vector)
    }

    // @@protoc_insertion_point(class_scope:WISE.ProjectProto.VectorCollection.Vector)
    private static final ca.wise.project.proto.VectorCollection.Vector DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.project.proto.VectorCollection.Vector();
    }

    public static ca.wise.project.proto.VectorCollection.Vector getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vector>
        PARSER = new com.google.protobuf.AbstractParser<Vector>() {
      @java.lang.Override
      public Vector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vector(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vector> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vector> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.project.proto.VectorCollection.Vector getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int VECTORS_FIELD_NUMBER = 2;
  private java.util.List<ca.wise.project.proto.VectorCollection.Vector> vectors_;
  /**
   * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<ca.wise.project.proto.VectorCollection.Vector> getVectorsList() {
    return vectors_;
  }
  /**
   * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public java.util.List<? extends ca.wise.project.proto.VectorCollection.VectorOrBuilder> 
      getVectorsOrBuilderList() {
    return vectors_;
  }
  /**
   * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public int getVectorsCount() {
    return vectors_.size();
  }
  /**
   * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.Vector getVectors(int index) {
    return vectors_.get(index);
  }
  /**
   * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.VectorOrBuilder getVectorsOrBuilder(
      int index) {
    return vectors_.get(index);
  }

  public static final int VECTORDATA_FIELD_NUMBER = 3;
  private java.util.List<ca.wise.grid.proto.CwfgmVectorFilter> vectorData_;
  /**
   * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
   */
  @java.lang.Override
  public java.util.List<ca.wise.grid.proto.CwfgmVectorFilter> getVectorDataList() {
    return vectorData_;
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ca.wise.grid.proto.CwfgmVectorFilterOrBuilder> 
      getVectorDataOrBuilderList() {
    return vectorData_;
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
   */
  @java.lang.Override
  public int getVectorDataCount() {
    return vectorData_.size();
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmVectorFilter getVectorData(int index) {
    return vectorData_.get(index);
  }
  /**
   * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
   */
  @java.lang.Override
  public ca.wise.grid.proto.CwfgmVectorFilterOrBuilder getVectorDataOrBuilder(
      int index) {
    return vectorData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    for (int i = 0; i < vectors_.size(); i++) {
      output.writeMessage(2, vectors_.get(i));
    }
    for (int i = 0; i < vectorData_.size(); i++) {
      output.writeMessage(3, vectorData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    for (int i = 0; i < vectors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, vectors_.get(i));
    }
    for (int i = 0; i < vectorData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, vectorData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.project.proto.VectorCollection)) {
      return super.equals(obj);
    }
    ca.wise.project.proto.VectorCollection other = (ca.wise.project.proto.VectorCollection) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getVectorsList()
        .equals(other.getVectorsList())) return false;
    if (!getVectorDataList()
        .equals(other.getVectorDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (getVectorsCount() > 0) {
      hash = (37 * hash) + VECTORS_FIELD_NUMBER;
      hash = (53 * hash) + getVectorsList().hashCode();
    }
    if (getVectorDataCount() > 0) {
      hash = (37 * hash) + VECTORDATA_FIELD_NUMBER;
      hash = (53 * hash) + getVectorDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.project.proto.VectorCollection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.VectorCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.VectorCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.project.proto.VectorCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.project.proto.VectorCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WISE.ProjectProto.VectorCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.ProjectProto.VectorCollection)
      ca.wise.project.proto.VectorCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.project.proto.VectorCollection.class, ca.wise.project.proto.VectorCollection.Builder.class);
    }

    // Construct using ca.wise.project.proto.VectorCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVectorsFieldBuilder();
        getVectorDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      if (vectorsBuilder_ == null) {
        vectors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        vectorsBuilder_.clear();
      }
      if (vectorDataBuilder_ == null) {
        vectorData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        vectorDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.project.proto.VectorCollectionOuterClass.internal_static_WISE_ProjectProto_VectorCollection_descriptor;
    }

    @java.lang.Override
    public ca.wise.project.proto.VectorCollection getDefaultInstanceForType() {
      return ca.wise.project.proto.VectorCollection.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.project.proto.VectorCollection build() {
      ca.wise.project.proto.VectorCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.project.proto.VectorCollection buildPartial() {
      ca.wise.project.proto.VectorCollection result = new ca.wise.project.proto.VectorCollection(this);
      int from_bitField0_ = bitField0_;
      result.version_ = version_;
      if (vectorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          vectors_ = java.util.Collections.unmodifiableList(vectors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vectors_ = vectors_;
      } else {
        result.vectors_ = vectorsBuilder_.build();
      }
      if (vectorDataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          vectorData_ = java.util.Collections.unmodifiableList(vectorData_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.vectorData_ = vectorData_;
      } else {
        result.vectorData_ = vectorDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.project.proto.VectorCollection) {
        return mergeFrom((ca.wise.project.proto.VectorCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.project.proto.VectorCollection other) {
      if (other == ca.wise.project.proto.VectorCollection.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (vectorsBuilder_ == null) {
        if (!other.vectors_.isEmpty()) {
          if (vectors_.isEmpty()) {
            vectors_ = other.vectors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVectorsIsMutable();
            vectors_.addAll(other.vectors_);
          }
          onChanged();
        }
      } else {
        if (!other.vectors_.isEmpty()) {
          if (vectorsBuilder_.isEmpty()) {
            vectorsBuilder_.dispose();
            vectorsBuilder_ = null;
            vectors_ = other.vectors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            vectorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVectorsFieldBuilder() : null;
          } else {
            vectorsBuilder_.addAllMessages(other.vectors_);
          }
        }
      }
      if (vectorDataBuilder_ == null) {
        if (!other.vectorData_.isEmpty()) {
          if (vectorData_.isEmpty()) {
            vectorData_ = other.vectorData_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureVectorDataIsMutable();
            vectorData_.addAll(other.vectorData_);
          }
          onChanged();
        }
      } else {
        if (!other.vectorData_.isEmpty()) {
          if (vectorDataBuilder_.isEmpty()) {
            vectorDataBuilder_.dispose();
            vectorDataBuilder_ = null;
            vectorData_ = other.vectorData_;
            bitField0_ = (bitField0_ & ~0x00000002);
            vectorDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVectorDataFieldBuilder() : null;
          } else {
            vectorDataBuilder_.addAllMessages(other.vectorData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.project.proto.VectorCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.project.proto.VectorCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<ca.wise.project.proto.VectorCollection.Vector> vectors_ =
      java.util.Collections.emptyList();
    private void ensureVectorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        vectors_ = new java.util.ArrayList<ca.wise.project.proto.VectorCollection.Vector>(vectors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.project.proto.VectorCollection.Vector, ca.wise.project.proto.VectorCollection.Vector.Builder, ca.wise.project.proto.VectorCollection.VectorOrBuilder> vectorsBuilder_;

    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<ca.wise.project.proto.VectorCollection.Vector> getVectorsList() {
      if (vectorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vectors_);
      } else {
        return vectorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public int getVectorsCount() {
      if (vectorsBuilder_ == null) {
        return vectors_.size();
      } else {
        return vectorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.Vector getVectors(int index) {
      if (vectorsBuilder_ == null) {
        return vectors_.get(index);
      } else {
        return vectorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setVectors(
        int index, ca.wise.project.proto.VectorCollection.Vector value) {
      if (vectorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorsIsMutable();
        vectors_.set(index, value);
        onChanged();
      } else {
        vectorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setVectors(
        int index, ca.wise.project.proto.VectorCollection.Vector.Builder builderForValue) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.set(index, builderForValue.build());
        onChanged();
      } else {
        vectorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addVectors(ca.wise.project.proto.VectorCollection.Vector value) {
      if (vectorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorsIsMutable();
        vectors_.add(value);
        onChanged();
      } else {
        vectorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addVectors(
        int index, ca.wise.project.proto.VectorCollection.Vector value) {
      if (vectorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorsIsMutable();
        vectors_.add(index, value);
        onChanged();
      } else {
        vectorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addVectors(
        ca.wise.project.proto.VectorCollection.Vector.Builder builderForValue) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.add(builderForValue.build());
        onChanged();
      } else {
        vectorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addVectors(
        int index, ca.wise.project.proto.VectorCollection.Vector.Builder builderForValue) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.add(index, builderForValue.build());
        onChanged();
      } else {
        vectorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder addAllVectors(
        java.lang.Iterable<? extends ca.wise.project.proto.VectorCollection.Vector> values) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vectors_);
        onChanged();
      } else {
        vectorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearVectors() {
      if (vectorsBuilder_ == null) {
        vectors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        vectorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder removeVectors(int index) {
      if (vectorsBuilder_ == null) {
        ensureVectorsIsMutable();
        vectors_.remove(index);
        onChanged();
      } else {
        vectorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.Vector.Builder getVectorsBuilder(
        int index) {
      return getVectorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.VectorOrBuilder getVectorsOrBuilder(
        int index) {
      if (vectorsBuilder_ == null) {
        return vectors_.get(index);  } else {
        return vectorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<? extends ca.wise.project.proto.VectorCollection.VectorOrBuilder> 
         getVectorsOrBuilderList() {
      if (vectorsBuilder_ != null) {
        return vectorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vectors_);
      }
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.Vector.Builder addVectorsBuilder() {
      return getVectorsFieldBuilder().addBuilder(
          ca.wise.project.proto.VectorCollection.Vector.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public ca.wise.project.proto.VectorCollection.Vector.Builder addVectorsBuilder(
        int index) {
      return getVectorsFieldBuilder().addBuilder(
          index, ca.wise.project.proto.VectorCollection.Vector.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.ProjectProto.VectorCollection.Vector vectors = 2 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.util.List<ca.wise.project.proto.VectorCollection.Vector.Builder> 
         getVectorsBuilderList() {
      return getVectorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.project.proto.VectorCollection.Vector, ca.wise.project.proto.VectorCollection.Vector.Builder, ca.wise.project.proto.VectorCollection.VectorOrBuilder> 
        getVectorsFieldBuilder() {
      if (vectorsBuilder_ == null) {
        vectorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.project.proto.VectorCollection.Vector, ca.wise.project.proto.VectorCollection.Vector.Builder, ca.wise.project.proto.VectorCollection.VectorOrBuilder>(
                vectors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        vectors_ = null;
      }
      return vectorsBuilder_;
    }

    private java.util.List<ca.wise.grid.proto.CwfgmVectorFilter> vectorData_ =
      java.util.Collections.emptyList();
    private void ensureVectorDataIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        vectorData_ = new java.util.ArrayList<ca.wise.grid.proto.CwfgmVectorFilter>(vectorData_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.grid.proto.CwfgmVectorFilter, ca.wise.grid.proto.CwfgmVectorFilter.Builder, ca.wise.grid.proto.CwfgmVectorFilterOrBuilder> vectorDataBuilder_;

    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public java.util.List<ca.wise.grid.proto.CwfgmVectorFilter> getVectorDataList() {
      if (vectorDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vectorData_);
      } else {
        return vectorDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public int getVectorDataCount() {
      if (vectorDataBuilder_ == null) {
        return vectorData_.size();
      } else {
        return vectorDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilter getVectorData(int index) {
      if (vectorDataBuilder_ == null) {
        return vectorData_.get(index);
      } else {
        return vectorDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder setVectorData(
        int index, ca.wise.grid.proto.CwfgmVectorFilter value) {
      if (vectorDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorDataIsMutable();
        vectorData_.set(index, value);
        onChanged();
      } else {
        vectorDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder setVectorData(
        int index, ca.wise.grid.proto.CwfgmVectorFilter.Builder builderForValue) {
      if (vectorDataBuilder_ == null) {
        ensureVectorDataIsMutable();
        vectorData_.set(index, builderForValue.build());
        onChanged();
      } else {
        vectorDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder addVectorData(ca.wise.grid.proto.CwfgmVectorFilter value) {
      if (vectorDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorDataIsMutable();
        vectorData_.add(value);
        onChanged();
      } else {
        vectorDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder addVectorData(
        int index, ca.wise.grid.proto.CwfgmVectorFilter value) {
      if (vectorDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVectorDataIsMutable();
        vectorData_.add(index, value);
        onChanged();
      } else {
        vectorDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder addVectorData(
        ca.wise.grid.proto.CwfgmVectorFilter.Builder builderForValue) {
      if (vectorDataBuilder_ == null) {
        ensureVectorDataIsMutable();
        vectorData_.add(builderForValue.build());
        onChanged();
      } else {
        vectorDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder addVectorData(
        int index, ca.wise.grid.proto.CwfgmVectorFilter.Builder builderForValue) {
      if (vectorDataBuilder_ == null) {
        ensureVectorDataIsMutable();
        vectorData_.add(index, builderForValue.build());
        onChanged();
      } else {
        vectorDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder addAllVectorData(
        java.lang.Iterable<? extends ca.wise.grid.proto.CwfgmVectorFilter> values) {
      if (vectorDataBuilder_ == null) {
        ensureVectorDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vectorData_);
        onChanged();
      } else {
        vectorDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder clearVectorData() {
      if (vectorDataBuilder_ == null) {
        vectorData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        vectorDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public Builder removeVectorData(int index) {
      if (vectorDataBuilder_ == null) {
        ensureVectorDataIsMutable();
        vectorData_.remove(index);
        onChanged();
      } else {
        vectorDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilter.Builder getVectorDataBuilder(
        int index) {
      return getVectorDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilterOrBuilder getVectorDataOrBuilder(
        int index) {
      if (vectorDataBuilder_ == null) {
        return vectorData_.get(index);  } else {
        return vectorDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public java.util.List<? extends ca.wise.grid.proto.CwfgmVectorFilterOrBuilder> 
         getVectorDataOrBuilderList() {
      if (vectorDataBuilder_ != null) {
        return vectorDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vectorData_);
      }
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilter.Builder addVectorDataBuilder() {
      return getVectorDataFieldBuilder().addBuilder(
          ca.wise.grid.proto.CwfgmVectorFilter.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public ca.wise.grid.proto.CwfgmVectorFilter.Builder addVectorDataBuilder(
        int index) {
      return getVectorDataFieldBuilder().addBuilder(
          index, ca.wise.grid.proto.CwfgmVectorFilter.getDefaultInstance());
    }
    /**
     * <code>repeated .WISE.GridProto.CwfgmVectorFilter vectorData = 3;</code>
     */
    public java.util.List<ca.wise.grid.proto.CwfgmVectorFilter.Builder> 
         getVectorDataBuilderList() {
      return getVectorDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.grid.proto.CwfgmVectorFilter, ca.wise.grid.proto.CwfgmVectorFilter.Builder, ca.wise.grid.proto.CwfgmVectorFilterOrBuilder> 
        getVectorDataFieldBuilder() {
      if (vectorDataBuilder_ == null) {
        vectorDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.grid.proto.CwfgmVectorFilter, ca.wise.grid.proto.CwfgmVectorFilter.Builder, ca.wise.grid.proto.CwfgmVectorFilterOrBuilder>(
                vectorData_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        vectorData_ = null;
      }
      return vectorDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.ProjectProto.VectorCollection)
  }

  // @@protoc_insertion_point(class_scope:WISE.ProjectProto.VectorCollection)
  private static final ca.wise.project.proto.VectorCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.project.proto.VectorCollection();
  }

  public static ca.wise.project.proto.VectorCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VectorCollection>
      PARSER = new com.google.protobuf.AbstractParser<VectorCollection>() {
    @java.lang.Override
    public VectorCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VectorCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VectorCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VectorCollection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.project.proto.VectorCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

