name: Test for Bug 172

on: workflow_dispatch

jobs:
  bugtest172:
    runs-on: ubuntu-20.04
    steps:

      - name: Download WISE Ubuntu 20.04
        uses: robinraju/release-downloader@v1.7
        with:
          # The source repository path.
          # Expected format {owner}/{repo}
          # Default: ${{ github.repository }}
          repository: "WISE-Developers/WISE_Application"

          # A flag to set the download target as latest release
          # The default value is 'false'
          latest: true

          # The github tag. e.g: v1.0.1
          # Download assets from a specific tag/version
          # tag: ""

          # The release id to download files from
          # releaseId: ""

          # The name of the file to download.
          # Use this field only to specify filenames other than tarball or zipball, if any.
          # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
          fileName: "wise-ubuntu2004-*.deb"
      

          # Download the attached tarball (*.tar.gz)
          tarBall: false

          # Download the attached zipball (*.zip)
          zipBall: false

          # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
          # It will create the target directory automatically if not present
          # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
          out-file-path: "test/wise"

          # Github access token to download files from private repositories
          # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          # eg: token: ${{ secrets.MY_TOKEN }}
         # token: ""

          # The URL of the Github API, only use this input if you are using Github Enterprise
          # Default: "https://api.github.com"
          # Use http(s)://[hostname]/api/v3 to access the API for GitHub Enterprise Server
         # github-api-url: ""
      - name: Install WISE
        run: sudo apt-get install -y /home/runner/work/WISE_Application/WISE_Application/test/wise/wise-ubuntu2004-1.0.0-beta.deb
      - name: Check exact Ubuntu Version
        run: cat /etc/issue; uname -a;
      - name: Test for Bug #172
        run: wise --version;
