name: DebTest

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  BOOST_VERSION: 1.81.0
  PROTO_VERSION: 21.10

jobs:

  debtest:
    runs-on: ubuntu-20.04
    steps:
      - name: Download WISE Ubuntu 20.04
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "WISE-Developers/WISE_Application"
          latest: true
          out-file-path: "test/wise"

       - name: Check 20.04 deb
        run: dpkg-deb --info /home/runner/work/WISE_Application/WISE_Application/test/wise/wise-ubuntu2004*.deb

       - name: Check 22.04 deb
        run: dpkg-deb --info /home/runner/work/WISE_Application/WISE_Application/test/wise/wise-ubuntu2204*.deb
        
      - name: Install WISE
        run: sudo apt-get install -y /home/runner/work/WISE_Application/WISE_Application/test/wise/wise-ubuntu2004*.deb
      
      
      
      
      
      
      
