name: smoketest

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  BOOST_VERSION: 1.81.0
  PROTO_VERSION: 21.10

jobs:

  smoketest_2004:
    runs-on: ubuntu-20.04
    steps:
      - name: Download WISE Ubuntu 20.04
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "WISE-Developers/WISE_Application"
          latest: true
          fileName: "wise-ubuntu2004*.deb"
          out-file-path: "test/wise"
          
      - name: Install WISE
        run: sudo apt-get install -y /home/runner/work/WISE_Application/WISE_Application/test/wise/wise-ubuntu2004*.deb     
        
      - name: Create Config File
        run: wget -c https://raw.githubusercontent.com/WISE-Developers/wise_demo/main/demo_data/test_helpers/sample_config.json -O /opt/jobs/config.json

      - name: Copy Deafaults.json
        run: cp /opt/api/files/defaults.json /opt/jobs/defaults.json
      
      - name: get the builder
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "WISE_Builder*.zip"
          out-file-path: "builder"
          repository: "WISE-Developers/WISE_Builder_Component"
          
      - name: Make the some important folders
        run: mkdir -p /opt/wise && mkdir -p /opt/builder && mkdir -p /opt/jobs && mkdir -p /opt/jobs/examples/test

      - name: unzip the builder
        run: unzip WISE_Builder*.zip -d /opt/builder && rm WISE_Builder*.zip

      - name: Install NodeJS and WISE JS API
        uses: actions/setup-node@v3
        with:
          node-version: 16

      
      - name: Download the WISE JS API and unzip the example job data
        run: git clone https://github.com/WISE-Developers/WISE_JS_API.git /opt/api && unzip /opt/api/files/dogrib.zip -d /opt/jobs/examples/test

      - name: Install the dependencies for the WISE JS API
        run: npm --prefix /opt/api i && npm config set WISE_JS_API:job_directory /opt/jobs
     
      - name: Install and run Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: Show Builder Version
        run: java -jar /usr/bin/WISE_Builder.jar --version
      
      - name: Build the model
        run: |
            cd /opt/api;
            nohup java -jar /opt/builder/WISE_Builder.jar -o json_v2 -j /opt/jobs -l 32479 2>&1 >/dev/null & echo $! > builder_pid.txt && sleep 5 && node /opt/api/dist/example_job.js && kill $(cat builder_pid.txt) && rm builder_pid.txt;
      
      
      - name: Run the model
        run: | 
            pwd;
            wise -r 4 -f 0 -t $(find /opt/jobs/ -maxdepth 1 -type d -name 'job_*' -print -quit)/job.fgmj
            
      - name: Examine outputs
        run: | 
              ls -lha /opt/jobs/
              tree /opt/jobs/
      
      
    
