name: Smoke Test

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  BOOST_VERSION: 1.81.0
  PROTO_VERSION: 21.10

jobs:

  smoketest:
    runs-on: ubuntu-20.04
    steps:
      - name: Download WISE Ubuntu 20.04
        uses: robinraju/release-downloader@v1.7
        with:
          # The source repository path.
          # Expected format {owner}/{repo}
          # Default: ${{ github.repository }}
          repository: "WISE-Developers/WISE_Application"

          # A flag to set the download target as latest release
          # The default value is 'false'
          latest: true

          # The github tag. e.g: v1.0.1
          # Download assets from a specific tag/version
          # tag: ""

          # The release id to download files from
          # releaseId: ""

          # The name of the file to download.
          # Use this field only to specify filenames other than tarball or zipball, if any.
          # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
          fileName: "wise-ubuntu2004-*.deb"
      

          # Download the attached tarball (*.tar.gz)
          tarBall: false

          # Download the attached zipball (*.zip)
          zipBall: false

          # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
          # It will create the target directory automatically if not present
          # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
          out-file-path: "test/wise"

          # Github access token to download files from private repositories
          # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          # eg: token: ${{ secrets.MY_TOKEN }}
         # token: ""

          # The URL of the Github API, only use this input if you are using Github Enterprise
          # Default: "https://api.github.com"
          # Use http(s)://[hostname]/api/v3 to access the API for GitHub Enterprise Server
         # github-api-url: ""
      - name: Install WISE
        run: sudo apt-get install -y /home/runner/work/WISE_Application/WISE_Application/test/wise/wise-ubuntu2004-1*beta.deb
      - name: Check exect Ubuntu Version
        run: cat /etc/issue; uname -a;
      # - name: show WISE version - Workaround for Bug #172
      #   run: wise -v | grep version
      - name: get the manager
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "WISE_Manager-*.zip"
          out-file-path: "manager/wise"
          repository: "WISE-Developers/WISE_Manager_Component"
      - name: get the builder
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "WISE_Builder-*.zip"
          out-file-path: "builder"
          repository: "WISE-Developers/WISE_Builder_Component"
      - name: unzip the builder
        run: ls -lha;cd builder; ls -lha; unzip *.zip
      - name: install the builder
        run: |
          ls -lha
          cd builder
          chmod 777 WISE_Builder.jar
          chmod -R 777 WISE_Builder_lib/
          ls -lha
          sudo cp -f WISE_Builder.jar /usr/bin/
          sudo cp -Rf WISE_Builder_lib/ /usr/bin/

      - name: Install NodeJS and WISE JS API
        uses: actions/setup-node@v3
        with:
          node-version: 16
   
      - run: npm init -y
      - run: npm i git+https://github.com/WISE-Developers/WISE_JS_API.git
      - run: cp node_modules/wise_js_api/package.json ./
      - run: npm i git+https://github.com/WISE-Developers/WISE_JS_API.git
      - run: npm install
      - run: npm config set WISE_JS_API:job_directory=/home/runner/work/WISE_Application/WISE_Application/jobs
      
      - name: Install and run Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - run: java -jar /usr/bin/WISE_Builder.jar --version
      - run: pwd
      
      
      #- name: install deps
      #  run: cp node_modules/wise_js_api/dist/example_job.js ./testjob.js;
      #- name: create a test job from a model script
      #  run: cp node_modules/wise_js_api/dist/example_job.js ./testjob.js;
      # - name: execute the test job
      #   run:  cd node_modules/wise_js_api/dist/;node example_job.js
      
      - name: create a test job from a model script
        run: cp node_modules/wise_js_api/dist/example_job.js ./testjob.js;
      - name: execute the test job
        run: node testjob.js

      # - name: Setup test job
      #   run: mkdir jobs; wget https://spyd.com/fgm.ca/datasets/bcjob.fgmj -O jobs/testjob.fgmj
